/* THIS FILE IS GENERATED DO NOT EDIT */
#ifndef GDNATIVE_API_STRUCT_H
#define GDNATIVE_API_STRUCT_H

#include <gdnative/gdnative.h>
#include <android/rebel_android.h>
#include <arvr/rebel_arvr.h>
#include <nativescript/rebel_nativescript.h>
#include <net/rebel_net.h>
#include <pluginscript/rebel_pluginscript.h>
#include <videodecoder/rebel_videodecoder.h>

#define GDNATIVE_API_INIT(options) do {  \
	extern const rebel_gdnative_core_api_struct *_gdnative_wrapper_api_struct;  \
	extern const rebel_gdnative_ext_nativescript_api_struct *_gdnative_wrapper_nativescript_api_struct;  \
	extern const rebel_gdnative_ext_pluginscript_api_struct *_gdnative_wrapper_pluginscript_api_struct;  \
	extern const rebel_gdnative_ext_android_api_struct *_gdnative_wrapper_android_api_struct;  \
	extern const rebel_gdnative_ext_arvr_api_struct *_gdnative_wrapper_arvr_api_struct;  \
	extern const rebel_gdnative_ext_videodecoder_api_struct *_gdnative_wrapper_videodecoder_api_struct;  \
	extern const rebel_gdnative_ext_net_api_struct *_gdnative_wrapper_net_api_struct;  \
	_gdnative_wrapper_api_struct = options->api_struct;  \
	for (unsigned int i = 0; i < _gdnative_wrapper_api_struct->num_extensions; i++) {   \
		switch (_gdnative_wrapper_api_struct->extensions[i]->type) {  \
			case GDNATIVE_EXT_NATIVESCRIPT:  \
				_gdnative_wrapper_nativescript_api_struct = (rebel_gdnative_ext_nativescript_api_struct *) _gdnative_wrapper_api_struct->extensions[i];  \
				break;  \
			case GDNATIVE_EXT_PLUGINSCRIPT:  \
				_gdnative_wrapper_pluginscript_api_struct = (rebel_gdnative_ext_pluginscript_api_struct *) _gdnative_wrapper_api_struct->extensions[i];  \
				break;  \
			case GDNATIVE_EXT_ANDROID:  \
				_gdnative_wrapper_android_api_struct = (rebel_gdnative_ext_android_api_struct *) _gdnative_wrapper_api_struct->extensions[i];  \
				break;  \
			case GDNATIVE_EXT_ARVR:  \
				_gdnative_wrapper_arvr_api_struct = (rebel_gdnative_ext_arvr_api_struct *) _gdnative_wrapper_api_struct->extensions[i];  \
				break;  \
			case GDNATIVE_EXT_VIDEODECODER:  \
				_gdnative_wrapper_videodecoder_api_struct = (rebel_gdnative_ext_videodecoder_api_struct *) _gdnative_wrapper_api_struct->extensions[i];  \
				break;  \
			case GDNATIVE_EXT_NET:  \
				_gdnative_wrapper_net_api_struct = (rebel_gdnative_ext_net_api_struct *) _gdnative_wrapper_api_struct->extensions[i];  \
				break;  \
		}  \
	}  \
 } while (0)

#ifdef __cplusplus
extern "C" {
#endif

enum GDNATIVE_API_TYPES {
	GDNATIVE_CORE,
	GDNATIVE_EXT_NATIVESCRIPT,
	GDNATIVE_EXT_PLUGINSCRIPT,
	GDNATIVE_EXT_ANDROID,
	GDNATIVE_EXT_ARVR,
	GDNATIVE_EXT_VIDEODECODER,
	GDNATIVE_EXT_NET,
};

typedef struct rebel_gdnative_ext_nativescript_1_1_api_struct {
	unsigned int type;
	rebel_gdnative_api_version version;
	const rebel_gdnative_api_struct *next;
	void (*rebel_nativescript_set_method_argument_information)(void *p_gdnative_handle, const char *p_name, const char *p_function_name, int p_num_args, const rebel_method_arg *p_args);
	void (*rebel_nativescript_set_class_documentation)(void *p_gdnative_handle, const char *p_name, rebel_string p_documentation);
	void (*rebel_nativescript_set_method_documentation)(void *p_gdnative_handle, const char *p_name, const char *p_function_name, rebel_string p_documentation);
	void (*rebel_nativescript_set_property_documentation)(void *p_gdnative_handle, const char *p_name, const char *p_path, rebel_string p_documentation);
	void (*rebel_nativescript_set_signal_documentation)(void *p_gdnative_handle, const char *p_name, const char *p_signal_name, rebel_string p_documentation);
	void (*rebel_nativescript_set_global_type_tag)(int p_idx, const char *p_name, const void *p_type_tag);
	const void *(*rebel_nativescript_get_global_type_tag)(int p_idx, const char *p_name);
	void (*rebel_nativescript_set_type_tag)(void *p_gdnative_handle, const char *p_name, const void *p_type_tag);
	const void *(*rebel_nativescript_get_type_tag)(const rebel_object *p_object);
	int (*rebel_nativescript_register_instance_binding_data_functions)(rebel_instance_binding_functions p_binding_functions);
	void (*rebel_nativescript_unregister_instance_binding_data_functions)(int p_idx);
	void *(*rebel_nativescript_get_instance_binding_data)(int p_idx, rebel_object *p_object);
	void (*rebel_nativescript_profiling_add_data)(const char *p_signature, uint64_t p_line);
} rebel_gdnative_ext_nativescript_1_1_api_struct;

typedef struct rebel_gdnative_ext_nativescript_api_struct {
	unsigned int type;
	rebel_gdnative_api_version version;
	const rebel_gdnative_api_struct *next;
	void (*rebel_nativescript_register_class)(void *p_gdnative_handle, const char *p_name, const char *p_base, rebel_instance_create_func p_create_func, rebel_instance_destroy_func p_destroy_func);
	void (*rebel_nativescript_register_tool_class)(void *p_gdnative_handle, const char *p_name, const char *p_base, rebel_instance_create_func p_create_func, rebel_instance_destroy_func p_destroy_func);
	void (*rebel_nativescript_register_method)(void *p_gdnative_handle, const char *p_name, const char *p_function_name, rebel_method_attributes p_attr, rebel_instance_method p_method);
	void (*rebel_nativescript_register_property)(void *p_gdnative_handle, const char *p_name, const char *p_path, rebel_property_attributes *p_attr, rebel_property_set_func p_set_func, rebel_property_get_func p_get_func);
	void (*rebel_nativescript_register_signal)(void *p_gdnative_handle, const char *p_name, const rebel_signal *p_signal);
	void *(*rebel_nativescript_get_userdata)(rebel_object *p_instance);
} rebel_gdnative_ext_nativescript_api_struct;

typedef struct rebel_gdnative_ext_pluginscript_api_struct {
	unsigned int type;
	rebel_gdnative_api_version version;
	const rebel_gdnative_api_struct *next;
	void (*rebel_pluginscript_register_language)(const rebel_pluginscript_language_desc *language_desc);
} rebel_gdnative_ext_pluginscript_api_struct;

typedef struct rebel_gdnative_ext_android_api_struct {
	unsigned int type;
	rebel_gdnative_api_version version;
	const rebel_gdnative_api_struct *next;
	JNIEnv*(*rebel_android_get_env)();
	jobject (*rebel_android_get_activity)();
	jobject (*rebel_android_get_surface)();
	bool (*rebel_android_is_activity_resumed)();
} rebel_gdnative_ext_android_api_struct;

typedef struct rebel_gdnative_ext_arvr_1_2_api_struct {
	unsigned int type;
	rebel_gdnative_api_version version;
	const rebel_gdnative_api_struct *next;
	void (*rebel_arvr_set_interface)(rebel_object *p_arvr_interface, const rebel_arvr_interface_gdnative *p_gdn_interface);
	rebel_int (*rebel_arvr_get_depthid)(rebel_rid *p_render_target);
} rebel_gdnative_ext_arvr_1_2_api_struct;

typedef struct rebel_gdnative_ext_arvr_api_struct {
	unsigned int type;
	rebel_gdnative_api_version version;
	const rebel_gdnative_api_struct *next;
	void (*rebel_arvr_register_interface)(const rebel_arvr_interface_gdnative *p_interface);
	rebel_real (*rebel_arvr_get_worldscale)();
	rebel_transform (*rebel_arvr_get_reference_frame)();
	void (*rebel_arvr_blit)(int p_eye, rebel_rid *p_render_target, rebel_rect2 *p_screen_rect);
	rebel_int (*rebel_arvr_get_texid)(rebel_rid *p_render_target);
	rebel_int (*rebel_arvr_add_controller)(char *p_device_name, rebel_int p_hand, rebel_bool p_tracks_orientation, rebel_bool p_tracks_position);
	void (*rebel_arvr_remove_controller)(rebel_int p_controller_id);
	void (*rebel_arvr_set_controller_transform)(rebel_int p_controller_id, rebel_transform *p_transform, rebel_bool p_tracks_orientation, rebel_bool p_tracks_position);
	void (*rebel_arvr_set_controller_button)(rebel_int p_controller_id, rebel_int p_button, rebel_bool p_is_pressed);
	void (*rebel_arvr_set_controller_axis)(rebel_int p_controller_id, rebel_int p_exis, rebel_real p_value, rebel_bool p_can_be_negative);
	rebel_real (*rebel_arvr_get_controller_rumble)(rebel_int p_controller_id);
} rebel_gdnative_ext_arvr_api_struct;

typedef struct rebel_gdnative_ext_videodecoder_api_struct {
	unsigned int type;
	rebel_gdnative_api_version version;
	const rebel_gdnative_api_struct *next;
	rebel_int (*rebel_videodecoder_file_read)(void *file_ptr, uint8_t *buf, int buf_size);
	int64_t (*rebel_videodecoder_file_seek)(void *file_ptr, int64_t pos, int whence);
	void (*rebel_videodecoder_register_decoder)(const rebel_videodecoder_interface_gdnative *p_interface);
} rebel_gdnative_ext_videodecoder_api_struct;

typedef struct rebel_gdnative_ext_net_3_2_api_struct {
	unsigned int type;
	rebel_gdnative_api_version version;
	const rebel_gdnative_api_struct *next;
	rebel_error (*rebel_net_set_webrtc_library)(const rebel_net_webrtc_library *p_library);
	void (*rebel_net_bind_webrtc_peer_connection)(rebel_object *p_obj, const rebel_net_webrtc_peer_connection *p_interface);
	void (*rebel_net_bind_webrtc_data_channel)(rebel_object *p_obj, const rebel_net_webrtc_data_channel *p_interface);
} rebel_gdnative_ext_net_3_2_api_struct;

typedef struct rebel_gdnative_ext_net_api_struct {
	unsigned int type;
	rebel_gdnative_api_version version;
	const rebel_gdnative_api_struct *next;
	void (*rebel_net_bind_stream_peer)(rebel_object *p_obj, const rebel_net_stream_peer *p_interface);
	void (*rebel_net_bind_packet_peer)(rebel_object *p_obj, const rebel_net_packet_peer *p_interface);
	void (*rebel_net_bind_multiplayer_peer)(rebel_object *p_obj, const rebel_net_multiplayer_peer *p_interface);
} rebel_gdnative_ext_net_api_struct;

typedef struct rebel_gdnative_core_1_2_api_struct {
	unsigned int type;
	rebel_gdnative_api_version version;
	const rebel_gdnative_api_struct *next;
	rebel_dictionary (*rebel_dictionary_duplicate)(const rebel_dictionary *p_self, const rebel_bool p_deep);
	rebel_vector3 (*rebel_vector3_move_toward)(const rebel_vector3 *p_self, const rebel_vector3 *p_to, const rebel_real p_delta);
	rebel_vector2 (*rebel_vector2_move_toward)(const rebel_vector2 *p_self, const rebel_vector2 *p_to, const rebel_real p_delta);
	rebel_int (*rebel_string_count)(const rebel_string *p_self, rebel_string p_what, rebel_int p_from, rebel_int p_to);
	rebel_int (*rebel_string_countn)(const rebel_string *p_self, rebel_string p_what, rebel_int p_from, rebel_int p_to);
	rebel_vector3 (*rebel_vector3_direction_to)(const rebel_vector3 *p_self, const rebel_vector3 *p_to);
	rebel_vector2 (*rebel_vector2_direction_to)(const rebel_vector2 *p_self, const rebel_vector2 *p_to);
	rebel_array (*rebel_array_slice)(const rebel_array *p_self, const rebel_int p_begin, const rebel_int p_end, const rebel_int p_step, const rebel_bool p_deep);
	rebel_bool (*rebel_pool_byte_array_empty)(const rebel_pool_byte_array *p_self);
	rebel_bool (*rebel_pool_int_array_empty)(const rebel_pool_int_array *p_self);
	rebel_bool (*rebel_pool_real_array_empty)(const rebel_pool_real_array *p_self);
	rebel_bool (*rebel_pool_string_array_empty)(const rebel_pool_string_array *p_self);
	rebel_bool (*rebel_pool_vector2_array_empty)(const rebel_pool_vector2_array *p_self);
	rebel_bool (*rebel_pool_vector3_array_empty)(const rebel_pool_vector3_array *p_self);
	rebel_bool (*rebel_pool_color_array_empty)(const rebel_pool_color_array *p_self);
	void *(*rebel_get_class_tag)(const rebel_string_name *p_class);
	rebel_object *(*rebel_object_cast_to)(const rebel_object *p_object, void *p_class_tag);
	rebel_object *(*rebel_instance_from_id)(rebel_int p_instance_id);
} rebel_gdnative_core_1_2_api_struct;

typedef struct rebel_gdnative_core_1_1_api_struct {
	unsigned int type;
	rebel_gdnative_api_version version;
	const rebel_gdnative_api_struct *next;
	rebel_int (*rebel_color_to_abgr32)(const rebel_color *p_self);
	rebel_int (*rebel_color_to_abgr64)(const rebel_color *p_self);
	rebel_int (*rebel_color_to_argb64)(const rebel_color *p_self);
	rebel_int (*rebel_color_to_rgba64)(const rebel_color *p_self);
	rebel_color (*rebel_color_darkened)(const rebel_color *p_self, const rebel_real p_amount);
	rebel_color (*rebel_color_from_hsv)(const rebel_color *p_self, const rebel_real p_h, const rebel_real p_s, const rebel_real p_v, const rebel_real p_a);
	rebel_color (*rebel_color_lightened)(const rebel_color *p_self, const rebel_real p_amount);
	rebel_array (*rebel_array_duplicate)(const rebel_array *p_self, const rebel_bool p_deep);
	rebel_variant (*rebel_array_max)(const rebel_array *p_self);
	rebel_variant (*rebel_array_min)(const rebel_array *p_self);
	void (*rebel_array_shuffle)(rebel_array *p_self);
	rebel_basis (*rebel_basis_slerp)(const rebel_basis *p_self, const rebel_basis *p_b, const rebel_real p_t);
	rebel_variant (*rebel_dictionary_get_with_default)(const rebel_dictionary *p_self, const rebel_variant *p_key, const rebel_variant *p_default);
	bool (*rebel_dictionary_erase_with_return)(rebel_dictionary *p_self, const rebel_variant *p_key);
	rebel_node_path (*rebel_node_path_get_as_property_path)(const rebel_node_path *p_self);
	void (*rebel_quat_set_axis_angle)(rebel_quat *p_self, const rebel_vector3 *p_axis, const rebel_real p_angle);
	rebel_rect2 (*rebel_rect2_grow_individual)(const rebel_rect2 *p_self, const rebel_real p_left, const rebel_real p_top, const rebel_real p_right, const rebel_real p_bottom);
	rebel_rect2 (*rebel_rect2_grow_margin)(const rebel_rect2 *p_self, const rebel_int p_margin, const rebel_real p_by);
	rebel_rect2 (*rebel_rect2_abs)(const rebel_rect2 *p_self);
	rebel_string (*rebel_string_dedent)(const rebel_string *p_self);
	rebel_string (*rebel_string_trim_prefix)(const rebel_string *p_self, const rebel_string *p_prefix);
	rebel_string (*rebel_string_trim_suffix)(const rebel_string *p_self, const rebel_string *p_suffix);
	rebel_string (*rebel_string_rstrip)(const rebel_string *p_self, const rebel_string *p_chars);
	rebel_pool_string_array (*rebel_string_rsplit)(const rebel_string *p_self, const rebel_string *p_divisor, const rebel_bool p_allow_empty, const rebel_int p_maxsplit);
	rebel_quat (*rebel_basis_get_quat)(const rebel_basis *p_self);
	void (*rebel_basis_set_quat)(rebel_basis *p_self, const rebel_quat *p_quat);
	void (*rebel_basis_set_axis_angle_scale)(rebel_basis *p_self, const rebel_vector3 *p_axis, rebel_real p_phi, const rebel_vector3 *p_scale);
	void (*rebel_basis_set_euler_scale)(rebel_basis *p_self, const rebel_vector3 *p_euler, const rebel_vector3 *p_scale);
	void (*rebel_basis_set_quat_scale)(rebel_basis *p_self, const rebel_quat *p_quat, const rebel_vector3 *p_scale);
	bool (*rebel_is_instance_valid)(const rebel_object *p_object);
	void (*rebel_quat_new_with_basis)(rebel_quat *r_dest, const rebel_basis *p_basis);
	void (*rebel_quat_new_with_euler)(rebel_quat *r_dest, const rebel_vector3 *p_euler);
	void (*rebel_transform_new_with_quat)(rebel_transform *r_dest, const rebel_quat *p_quat);
	rebel_string (*rebel_variant_get_operator_name)(rebel_variant_operator p_op);
	void (*rebel_variant_evaluate)(rebel_variant_operator p_op, const rebel_variant *p_a, const rebel_variant *p_b, rebel_variant *r_ret, rebel_bool *r_valid);
} rebel_gdnative_core_1_1_api_struct;

typedef struct rebel_gdnative_core_api_struct {
	unsigned int type;
	rebel_gdnative_api_version version;
	const rebel_gdnative_api_struct *next;
	unsigned int num_extensions;
	const rebel_gdnative_api_struct **extensions;
	void (*rebel_color_new_rgba)(rebel_color *r_dest, const rebel_real p_r, const rebel_real p_g, const rebel_real p_b, const rebel_real p_a);
	void (*rebel_color_new_rgb)(rebel_color *r_dest, const rebel_real p_r, const rebel_real p_g, const rebel_real p_b);
	rebel_real (*rebel_color_get_r)(const rebel_color *p_self);
	void (*rebel_color_set_r)(rebel_color *p_self, const rebel_real r);
	rebel_real (*rebel_color_get_g)(const rebel_color *p_self);
	void (*rebel_color_set_g)(rebel_color *p_self, const rebel_real g);
	rebel_real (*rebel_color_get_b)(const rebel_color *p_self);
	void (*rebel_color_set_b)(rebel_color *p_self, const rebel_real b);
	rebel_real (*rebel_color_get_a)(const rebel_color *p_self);
	void (*rebel_color_set_a)(rebel_color *p_self, const rebel_real a);
	rebel_real (*rebel_color_get_h)(const rebel_color *p_self);
	rebel_real (*rebel_color_get_s)(const rebel_color *p_self);
	rebel_real (*rebel_color_get_v)(const rebel_color *p_self);
	rebel_string (*rebel_color_as_string)(const rebel_color *p_self);
	rebel_int (*rebel_color_to_rgba32)(const rebel_color *p_self);
	rebel_int (*rebel_color_to_argb32)(const rebel_color *p_self);
	rebel_real (*rebel_color_gray)(const rebel_color *p_self);
	rebel_color (*rebel_color_inverted)(const rebel_color *p_self);
	rebel_color (*rebel_color_contrasted)(const rebel_color *p_self);
	rebel_color (*rebel_color_linear_interpolate)(const rebel_color *p_self, const rebel_color *p_b, const rebel_real p_t);
	rebel_color (*rebel_color_blend)(const rebel_color *p_self, const rebel_color *p_over);
	rebel_string (*rebel_color_to_html)(const rebel_color *p_self, const rebel_bool p_with_alpha);
	rebel_bool (*rebel_color_operator_equal)(const rebel_color *p_self, const rebel_color *p_b);
	rebel_bool (*rebel_color_operator_less)(const rebel_color *p_self, const rebel_color *p_b);
	void (*rebel_vector2_new)(rebel_vector2 *r_dest, const rebel_real p_x, const rebel_real p_y);
	rebel_string (*rebel_vector2_as_string)(const rebel_vector2 *p_self);
	rebel_vector2 (*rebel_vector2_normalized)(const rebel_vector2 *p_self);
	rebel_real (*rebel_vector2_length)(const rebel_vector2 *p_self);
	rebel_real (*rebel_vector2_angle)(const rebel_vector2 *p_self);
	rebel_real (*rebel_vector2_length_squared)(const rebel_vector2 *p_self);
	rebel_bool (*rebel_vector2_is_normalized)(const rebel_vector2 *p_self);
	rebel_real (*rebel_vector2_distance_to)(const rebel_vector2 *p_self, const rebel_vector2 *p_to);
	rebel_real (*rebel_vector2_distance_squared_to)(const rebel_vector2 *p_self, const rebel_vector2 *p_to);
	rebel_real (*rebel_vector2_angle_to)(const rebel_vector2 *p_self, const rebel_vector2 *p_to);
	rebel_real (*rebel_vector2_angle_to_point)(const rebel_vector2 *p_self, const rebel_vector2 *p_to);
	rebel_vector2 (*rebel_vector2_linear_interpolate)(const rebel_vector2 *p_self, const rebel_vector2 *p_b, const rebel_real p_t);
	rebel_vector2 (*rebel_vector2_cubic_interpolate)(const rebel_vector2 *p_self, const rebel_vector2 *p_b, const rebel_vector2 *p_pre_a, const rebel_vector2 *p_post_b, const rebel_real p_t);
	rebel_vector2 (*rebel_vector2_rotated)(const rebel_vector2 *p_self, const rebel_real p_phi);
	rebel_vector2 (*rebel_vector2_tangent)(const rebel_vector2 *p_self);
	rebel_vector2 (*rebel_vector2_floor)(const rebel_vector2 *p_self);
	rebel_vector2 (*rebel_vector2_snapped)(const rebel_vector2 *p_self, const rebel_vector2 *p_by);
	rebel_real (*rebel_vector2_aspect)(const rebel_vector2 *p_self);
	rebel_real (*rebel_vector2_dot)(const rebel_vector2 *p_self, const rebel_vector2 *p_with);
	rebel_vector2 (*rebel_vector2_slide)(const rebel_vector2 *p_self, const rebel_vector2 *p_n);
	rebel_vector2 (*rebel_vector2_bounce)(const rebel_vector2 *p_self, const rebel_vector2 *p_n);
	rebel_vector2 (*rebel_vector2_reflect)(const rebel_vector2 *p_self, const rebel_vector2 *p_n);
	rebel_vector2 (*rebel_vector2_abs)(const rebel_vector2 *p_self);
	rebel_vector2 (*rebel_vector2_clamped)(const rebel_vector2 *p_self, const rebel_real p_length);
	rebel_vector2 (*rebel_vector2_operator_add)(const rebel_vector2 *p_self, const rebel_vector2 *p_b);
	rebel_vector2 (*rebel_vector2_operator_subtract)(const rebel_vector2 *p_self, const rebel_vector2 *p_b);
	rebel_vector2 (*rebel_vector2_operator_multiply_vector)(const rebel_vector2 *p_self, const rebel_vector2 *p_b);
	rebel_vector2 (*rebel_vector2_operator_multiply_scalar)(const rebel_vector2 *p_self, const rebel_real p_b);
	rebel_vector2 (*rebel_vector2_operator_divide_vector)(const rebel_vector2 *p_self, const rebel_vector2 *p_b);
	rebel_vector2 (*rebel_vector2_operator_divide_scalar)(const rebel_vector2 *p_self, const rebel_real p_b);
	rebel_bool (*rebel_vector2_operator_equal)(const rebel_vector2 *p_self, const rebel_vector2 *p_b);
	rebel_bool (*rebel_vector2_operator_less)(const rebel_vector2 *p_self, const rebel_vector2 *p_b);
	rebel_vector2 (*rebel_vector2_operator_neg)(const rebel_vector2 *p_self);
	void (*rebel_vector2_set_x)(rebel_vector2 *p_self, const rebel_real p_x);
	void (*rebel_vector2_set_y)(rebel_vector2 *p_self, const rebel_real p_y);
	rebel_real (*rebel_vector2_get_x)(const rebel_vector2 *p_self);
	rebel_real (*rebel_vector2_get_y)(const rebel_vector2 *p_self);
	void (*rebel_quat_new)(rebel_quat *r_dest, const rebel_real p_x, const rebel_real p_y, const rebel_real p_z, const rebel_real p_w);
	void (*rebel_quat_new_with_axis_angle)(rebel_quat *r_dest, const rebel_vector3 *p_axis, const rebel_real p_angle);
	rebel_real (*rebel_quat_get_x)(const rebel_quat *p_self);
	void (*rebel_quat_set_x)(rebel_quat *p_self, const rebel_real val);
	rebel_real (*rebel_quat_get_y)(const rebel_quat *p_self);
	void (*rebel_quat_set_y)(rebel_quat *p_self, const rebel_real val);
	rebel_real (*rebel_quat_get_z)(const rebel_quat *p_self);
	void (*rebel_quat_set_z)(rebel_quat *p_self, const rebel_real val);
	rebel_real (*rebel_quat_get_w)(const rebel_quat *p_self);
	void (*rebel_quat_set_w)(rebel_quat *p_self, const rebel_real val);
	rebel_string (*rebel_quat_as_string)(const rebel_quat *p_self);
	rebel_real (*rebel_quat_length)(const rebel_quat *p_self);
	rebel_real (*rebel_quat_length_squared)(const rebel_quat *p_self);
	rebel_quat (*rebel_quat_normalized)(const rebel_quat *p_self);
	rebel_bool (*rebel_quat_is_normalized)(const rebel_quat *p_self);
	rebel_quat (*rebel_quat_inverse)(const rebel_quat *p_self);
	rebel_real (*rebel_quat_dot)(const rebel_quat *p_self, const rebel_quat *p_b);
	rebel_vector3 (*rebel_quat_xform)(const rebel_quat *p_self, const rebel_vector3 *p_v);
	rebel_quat (*rebel_quat_slerp)(const rebel_quat *p_self, const rebel_quat *p_b, const rebel_real p_t);
	rebel_quat (*rebel_quat_slerpni)(const rebel_quat *p_self, const rebel_quat *p_b, const rebel_real p_t);
	rebel_quat (*rebel_quat_cubic_slerp)(const rebel_quat *p_self, const rebel_quat *p_b, const rebel_quat *p_pre_a, const rebel_quat *p_post_b, const rebel_real p_t);
	rebel_quat (*rebel_quat_operator_multiply)(const rebel_quat *p_self, const rebel_real p_b);
	rebel_quat (*rebel_quat_operator_add)(const rebel_quat *p_self, const rebel_quat *p_b);
	rebel_quat (*rebel_quat_operator_subtract)(const rebel_quat *p_self, const rebel_quat *p_b);
	rebel_quat (*rebel_quat_operator_divide)(const rebel_quat *p_self, const rebel_real p_b);
	rebel_bool (*rebel_quat_operator_equal)(const rebel_quat *p_self, const rebel_quat *p_b);
	rebel_quat (*rebel_quat_operator_neg)(const rebel_quat *p_self);
	void (*rebel_basis_new_with_rows)(rebel_basis *r_dest, const rebel_vector3 *p_x_axis, const rebel_vector3 *p_y_axis, const rebel_vector3 *p_z_axis);
	void (*rebel_basis_new_with_axis_and_angle)(rebel_basis *r_dest, const rebel_vector3 *p_axis, const rebel_real p_phi);
	void (*rebel_basis_new_with_euler)(rebel_basis *r_dest, const rebel_vector3 *p_euler);
	rebel_string (*rebel_basis_as_string)(const rebel_basis *p_self);
	rebel_basis (*rebel_basis_inverse)(const rebel_basis *p_self);
	rebel_basis (*rebel_basis_transposed)(const rebel_basis *p_self);
	rebel_basis (*rebel_basis_orthonormalized)(const rebel_basis *p_self);
	rebel_real (*rebel_basis_determinant)(const rebel_basis *p_self);
	rebel_basis (*rebel_basis_rotated)(const rebel_basis *p_self, const rebel_vector3 *p_axis, const rebel_real p_phi);
	rebel_basis (*rebel_basis_scaled)(const rebel_basis *p_self, const rebel_vector3 *p_scale);
	rebel_vector3 (*rebel_basis_get_scale)(const rebel_basis *p_self);
	rebel_vector3 (*rebel_basis_get_euler)(const rebel_basis *p_self);
	rebel_real (*rebel_basis_tdotx)(const rebel_basis *p_self, const rebel_vector3 *p_with);
	rebel_real (*rebel_basis_tdoty)(const rebel_basis *p_self, const rebel_vector3 *p_with);
	rebel_real (*rebel_basis_tdotz)(const rebel_basis *p_self, const rebel_vector3 *p_with);
	rebel_vector3 (*rebel_basis_xform)(const rebel_basis *p_self, const rebel_vector3 *p_v);
	rebel_vector3 (*rebel_basis_xform_inv)(const rebel_basis *p_self, const rebel_vector3 *p_v);
	rebel_int (*rebel_basis_get_orthogonal_index)(const rebel_basis *p_self);
	void (*rebel_basis_new)(rebel_basis *r_dest);
	void (*rebel_basis_new_with_euler_quat)(rebel_basis *r_dest, const rebel_quat *p_euler);
	void (*rebel_basis_get_elements)(const rebel_basis *p_self, rebel_vector3 *p_elements);
	rebel_vector3 (*rebel_basis_get_axis)(const rebel_basis *p_self, const rebel_int p_axis);
	void (*rebel_basis_set_axis)(rebel_basis *p_self, const rebel_int p_axis, const rebel_vector3 *p_value);
	rebel_vector3 (*rebel_basis_get_row)(const rebel_basis *p_self, const rebel_int p_row);
	void (*rebel_basis_set_row)(rebel_basis *p_self, const rebel_int p_row, const rebel_vector3 *p_value);
	rebel_bool (*rebel_basis_operator_equal)(const rebel_basis *p_self, const rebel_basis *p_b);
	rebel_basis (*rebel_basis_operator_add)(const rebel_basis *p_self, const rebel_basis *p_b);
	rebel_basis (*rebel_basis_operator_subtract)(const rebel_basis *p_self, const rebel_basis *p_b);
	rebel_basis (*rebel_basis_operator_multiply_vector)(const rebel_basis *p_self, const rebel_basis *p_b);
	rebel_basis (*rebel_basis_operator_multiply_scalar)(const rebel_basis *p_self, const rebel_real p_b);
	void (*rebel_vector3_new)(rebel_vector3 *r_dest, const rebel_real p_x, const rebel_real p_y, const rebel_real p_z);
	rebel_string (*rebel_vector3_as_string)(const rebel_vector3 *p_self);
	rebel_int (*rebel_vector3_min_axis)(const rebel_vector3 *p_self);
	rebel_int (*rebel_vector3_max_axis)(const rebel_vector3 *p_self);
	rebel_real (*rebel_vector3_length)(const rebel_vector3 *p_self);
	rebel_real (*rebel_vector3_length_squared)(const rebel_vector3 *p_self);
	rebel_bool (*rebel_vector3_is_normalized)(const rebel_vector3 *p_self);
	rebel_vector3 (*rebel_vector3_normalized)(const rebel_vector3 *p_self);
	rebel_vector3 (*rebel_vector3_inverse)(const rebel_vector3 *p_self);
	rebel_vector3 (*rebel_vector3_snapped)(const rebel_vector3 *p_self, const rebel_vector3 *p_by);
	rebel_vector3 (*rebel_vector3_rotated)(const rebel_vector3 *p_self, const rebel_vector3 *p_axis, const rebel_real p_phi);
	rebel_vector3 (*rebel_vector3_linear_interpolate)(const rebel_vector3 *p_self, const rebel_vector3 *p_b, const rebel_real p_t);
	rebel_vector3 (*rebel_vector3_cubic_interpolate)(const rebel_vector3 *p_self, const rebel_vector3 *p_b, const rebel_vector3 *p_pre_a, const rebel_vector3 *p_post_b, const rebel_real p_t);
	rebel_real (*rebel_vector3_dot)(const rebel_vector3 *p_self, const rebel_vector3 *p_b);
	rebel_vector3 (*rebel_vector3_cross)(const rebel_vector3 *p_self, const rebel_vector3 *p_b);
	rebel_basis (*rebel_vector3_outer)(const rebel_vector3 *p_self, const rebel_vector3 *p_b);
	rebel_basis (*rebel_vector3_to_diagonal_matrix)(const rebel_vector3 *p_self);
	rebel_vector3 (*rebel_vector3_abs)(const rebel_vector3 *p_self);
	rebel_vector3 (*rebel_vector3_floor)(const rebel_vector3 *p_self);
	rebel_vector3 (*rebel_vector3_ceil)(const rebel_vector3 *p_self);
	rebel_real (*rebel_vector3_distance_to)(const rebel_vector3 *p_self, const rebel_vector3 *p_b);
	rebel_real (*rebel_vector3_distance_squared_to)(const rebel_vector3 *p_self, const rebel_vector3 *p_b);
	rebel_real (*rebel_vector3_angle_to)(const rebel_vector3 *p_self, const rebel_vector3 *p_to);
	rebel_vector3 (*rebel_vector3_slide)(const rebel_vector3 *p_self, const rebel_vector3 *p_n);
	rebel_vector3 (*rebel_vector3_bounce)(const rebel_vector3 *p_self, const rebel_vector3 *p_n);
	rebel_vector3 (*rebel_vector3_reflect)(const rebel_vector3 *p_self, const rebel_vector3 *p_n);
	rebel_vector3 (*rebel_vector3_operator_add)(const rebel_vector3 *p_self, const rebel_vector3 *p_b);
	rebel_vector3 (*rebel_vector3_operator_subtract)(const rebel_vector3 *p_self, const rebel_vector3 *p_b);
	rebel_vector3 (*rebel_vector3_operator_multiply_vector)(const rebel_vector3 *p_self, const rebel_vector3 *p_b);
	rebel_vector3 (*rebel_vector3_operator_multiply_scalar)(const rebel_vector3 *p_self, const rebel_real p_b);
	rebel_vector3 (*rebel_vector3_operator_divide_vector)(const rebel_vector3 *p_self, const rebel_vector3 *p_b);
	rebel_vector3 (*rebel_vector3_operator_divide_scalar)(const rebel_vector3 *p_self, const rebel_real p_b);
	rebel_bool (*rebel_vector3_operator_equal)(const rebel_vector3 *p_self, const rebel_vector3 *p_b);
	rebel_bool (*rebel_vector3_operator_less)(const rebel_vector3 *p_self, const rebel_vector3 *p_b);
	rebel_vector3 (*rebel_vector3_operator_neg)(const rebel_vector3 *p_self);
	void (*rebel_vector3_set_axis)(rebel_vector3 *p_self, const rebel_vector3_axis p_axis, const rebel_real p_val);
	rebel_real (*rebel_vector3_get_axis)(const rebel_vector3 *p_self, const rebel_vector3_axis p_axis);
	void (*rebel_pool_byte_array_new)(rebel_pool_byte_array *r_dest);
	void (*rebel_pool_byte_array_new_copy)(rebel_pool_byte_array *r_dest, const rebel_pool_byte_array *p_src);
	void (*rebel_pool_byte_array_new_with_array)(rebel_pool_byte_array *r_dest, const rebel_array *p_a);
	void (*rebel_pool_byte_array_append)(rebel_pool_byte_array *p_self, const uint8_t p_data);
	void (*rebel_pool_byte_array_append_array)(rebel_pool_byte_array *p_self, const rebel_pool_byte_array *p_array);
	rebel_error (*rebel_pool_byte_array_insert)(rebel_pool_byte_array *p_self, const rebel_int p_idx, const uint8_t p_data);
	void (*rebel_pool_byte_array_invert)(rebel_pool_byte_array *p_self);
	void (*rebel_pool_byte_array_push_back)(rebel_pool_byte_array *p_self, const uint8_t p_data);
	void (*rebel_pool_byte_array_remove)(rebel_pool_byte_array *p_self, const rebel_int p_idx);
	void (*rebel_pool_byte_array_resize)(rebel_pool_byte_array *p_self, const rebel_int p_size);
	rebel_pool_byte_array_read_access *(*rebel_pool_byte_array_read)(const rebel_pool_byte_array *p_self);
	rebel_pool_byte_array_write_access *(*rebel_pool_byte_array_write)(rebel_pool_byte_array *p_self);
	void (*rebel_pool_byte_array_set)(rebel_pool_byte_array *p_self, const rebel_int p_idx, const uint8_t p_data);
	uint8_t (*rebel_pool_byte_array_get)(const rebel_pool_byte_array *p_self, const rebel_int p_idx);
	rebel_int (*rebel_pool_byte_array_size)(const rebel_pool_byte_array *p_self);
	void (*rebel_pool_byte_array_destroy)(rebel_pool_byte_array *p_self);
	void (*rebel_pool_int_array_new)(rebel_pool_int_array *r_dest);
	void (*rebel_pool_int_array_new_copy)(rebel_pool_int_array *r_dest, const rebel_pool_int_array *p_src);
	void (*rebel_pool_int_array_new_with_array)(rebel_pool_int_array *r_dest, const rebel_array *p_a);
	void (*rebel_pool_int_array_append)(rebel_pool_int_array *p_self, const rebel_int p_data);
	void (*rebel_pool_int_array_append_array)(rebel_pool_int_array *p_self, const rebel_pool_int_array *p_array);
	rebel_error (*rebel_pool_int_array_insert)(rebel_pool_int_array *p_self, const rebel_int p_idx, const rebel_int p_data);
	void (*rebel_pool_int_array_invert)(rebel_pool_int_array *p_self);
	void (*rebel_pool_int_array_push_back)(rebel_pool_int_array *p_self, const rebel_int p_data);
	void (*rebel_pool_int_array_remove)(rebel_pool_int_array *p_self, const rebel_int p_idx);
	void (*rebel_pool_int_array_resize)(rebel_pool_int_array *p_self, const rebel_int p_size);
	rebel_pool_int_array_read_access *(*rebel_pool_int_array_read)(const rebel_pool_int_array *p_self);
	rebel_pool_int_array_write_access *(*rebel_pool_int_array_write)(rebel_pool_int_array *p_self);
	void (*rebel_pool_int_array_set)(rebel_pool_int_array *p_self, const rebel_int p_idx, const rebel_int p_data);
	rebel_int (*rebel_pool_int_array_get)(const rebel_pool_int_array *p_self, const rebel_int p_idx);
	rebel_int (*rebel_pool_int_array_size)(const rebel_pool_int_array *p_self);
	void (*rebel_pool_int_array_destroy)(rebel_pool_int_array *p_self);
	void (*rebel_pool_real_array_new)(rebel_pool_real_array *r_dest);
	void (*rebel_pool_real_array_new_copy)(rebel_pool_real_array *r_dest, const rebel_pool_real_array *p_src);
	void (*rebel_pool_real_array_new_with_array)(rebel_pool_real_array *r_dest, const rebel_array *p_a);
	void (*rebel_pool_real_array_append)(rebel_pool_real_array *p_self, const rebel_real p_data);
	void (*rebel_pool_real_array_append_array)(rebel_pool_real_array *p_self, const rebel_pool_real_array *p_array);
	rebel_error (*rebel_pool_real_array_insert)(rebel_pool_real_array *p_self, const rebel_int p_idx, const rebel_real p_data);
	void (*rebel_pool_real_array_invert)(rebel_pool_real_array *p_self);
	void (*rebel_pool_real_array_push_back)(rebel_pool_real_array *p_self, const rebel_real p_data);
	void (*rebel_pool_real_array_remove)(rebel_pool_real_array *p_self, const rebel_int p_idx);
	void (*rebel_pool_real_array_resize)(rebel_pool_real_array *p_self, const rebel_int p_size);
	rebel_pool_real_array_read_access *(*rebel_pool_real_array_read)(const rebel_pool_real_array *p_self);
	rebel_pool_real_array_write_access *(*rebel_pool_real_array_write)(rebel_pool_real_array *p_self);
	void (*rebel_pool_real_array_set)(rebel_pool_real_array *p_self, const rebel_int p_idx, const rebel_real p_data);
	rebel_real (*rebel_pool_real_array_get)(const rebel_pool_real_array *p_self, const rebel_int p_idx);
	rebel_int (*rebel_pool_real_array_size)(const rebel_pool_real_array *p_self);
	void (*rebel_pool_real_array_destroy)(rebel_pool_real_array *p_self);
	void (*rebel_pool_string_array_new)(rebel_pool_string_array *r_dest);
	void (*rebel_pool_string_array_new_copy)(rebel_pool_string_array *r_dest, const rebel_pool_string_array *p_src);
	void (*rebel_pool_string_array_new_with_array)(rebel_pool_string_array *r_dest, const rebel_array *p_a);
	void (*rebel_pool_string_array_append)(rebel_pool_string_array *p_self, const rebel_string *p_data);
	void (*rebel_pool_string_array_append_array)(rebel_pool_string_array *p_self, const rebel_pool_string_array *p_array);
	rebel_error (*rebel_pool_string_array_insert)(rebel_pool_string_array *p_self, const rebel_int p_idx, const rebel_string *p_data);
	void (*rebel_pool_string_array_invert)(rebel_pool_string_array *p_self);
	void (*rebel_pool_string_array_push_back)(rebel_pool_string_array *p_self, const rebel_string *p_data);
	void (*rebel_pool_string_array_remove)(rebel_pool_string_array *p_self, const rebel_int p_idx);
	void (*rebel_pool_string_array_resize)(rebel_pool_string_array *p_self, const rebel_int p_size);
	rebel_pool_string_array_read_access *(*rebel_pool_string_array_read)(const rebel_pool_string_array *p_self);
	rebel_pool_string_array_write_access *(*rebel_pool_string_array_write)(rebel_pool_string_array *p_self);
	void (*rebel_pool_string_array_set)(rebel_pool_string_array *p_self, const rebel_int p_idx, const rebel_string *p_data);
	rebel_string (*rebel_pool_string_array_get)(const rebel_pool_string_array *p_self, const rebel_int p_idx);
	rebel_int (*rebel_pool_string_array_size)(const rebel_pool_string_array *p_self);
	void (*rebel_pool_string_array_destroy)(rebel_pool_string_array *p_self);
	void (*rebel_pool_vector2_array_new)(rebel_pool_vector2_array *r_dest);
	void (*rebel_pool_vector2_array_new_copy)(rebel_pool_vector2_array *r_dest, const rebel_pool_vector2_array *p_src);
	void (*rebel_pool_vector2_array_new_with_array)(rebel_pool_vector2_array *r_dest, const rebel_array *p_a);
	void (*rebel_pool_vector2_array_append)(rebel_pool_vector2_array *p_self, const rebel_vector2 *p_data);
	void (*rebel_pool_vector2_array_append_array)(rebel_pool_vector2_array *p_self, const rebel_pool_vector2_array *p_array);
	rebel_error (*rebel_pool_vector2_array_insert)(rebel_pool_vector2_array *p_self, const rebel_int p_idx, const rebel_vector2 *p_data);
	void (*rebel_pool_vector2_array_invert)(rebel_pool_vector2_array *p_self);
	void (*rebel_pool_vector2_array_push_back)(rebel_pool_vector2_array *p_self, const rebel_vector2 *p_data);
	void (*rebel_pool_vector2_array_remove)(rebel_pool_vector2_array *p_self, const rebel_int p_idx);
	void (*rebel_pool_vector2_array_resize)(rebel_pool_vector2_array *p_self, const rebel_int p_size);
	rebel_pool_vector2_array_read_access *(*rebel_pool_vector2_array_read)(const rebel_pool_vector2_array *p_self);
	rebel_pool_vector2_array_write_access *(*rebel_pool_vector2_array_write)(rebel_pool_vector2_array *p_self);
	void (*rebel_pool_vector2_array_set)(rebel_pool_vector2_array *p_self, const rebel_int p_idx, const rebel_vector2 *p_data);
	rebel_vector2 (*rebel_pool_vector2_array_get)(const rebel_pool_vector2_array *p_self, const rebel_int p_idx);
	rebel_int (*rebel_pool_vector2_array_size)(const rebel_pool_vector2_array *p_self);
	void (*rebel_pool_vector2_array_destroy)(rebel_pool_vector2_array *p_self);
	void (*rebel_pool_vector3_array_new)(rebel_pool_vector3_array *r_dest);
	void (*rebel_pool_vector3_array_new_copy)(rebel_pool_vector3_array *r_dest, const rebel_pool_vector3_array *p_src);
	void (*rebel_pool_vector3_array_new_with_array)(rebel_pool_vector3_array *r_dest, const rebel_array *p_a);
	void (*rebel_pool_vector3_array_append)(rebel_pool_vector3_array *p_self, const rebel_vector3 *p_data);
	void (*rebel_pool_vector3_array_append_array)(rebel_pool_vector3_array *p_self, const rebel_pool_vector3_array *p_array);
	rebel_error (*rebel_pool_vector3_array_insert)(rebel_pool_vector3_array *p_self, const rebel_int p_idx, const rebel_vector3 *p_data);
	void (*rebel_pool_vector3_array_invert)(rebel_pool_vector3_array *p_self);
	void (*rebel_pool_vector3_array_push_back)(rebel_pool_vector3_array *p_self, const rebel_vector3 *p_data);
	void (*rebel_pool_vector3_array_remove)(rebel_pool_vector3_array *p_self, const rebel_int p_idx);
	void (*rebel_pool_vector3_array_resize)(rebel_pool_vector3_array *p_self, const rebel_int p_size);
	rebel_pool_vector3_array_read_access *(*rebel_pool_vector3_array_read)(const rebel_pool_vector3_array *p_self);
	rebel_pool_vector3_array_write_access *(*rebel_pool_vector3_array_write)(rebel_pool_vector3_array *p_self);
	void (*rebel_pool_vector3_array_set)(rebel_pool_vector3_array *p_self, const rebel_int p_idx, const rebel_vector3 *p_data);
	rebel_vector3 (*rebel_pool_vector3_array_get)(const rebel_pool_vector3_array *p_self, const rebel_int p_idx);
	rebel_int (*rebel_pool_vector3_array_size)(const rebel_pool_vector3_array *p_self);
	void (*rebel_pool_vector3_array_destroy)(rebel_pool_vector3_array *p_self);
	void (*rebel_pool_color_array_new)(rebel_pool_color_array *r_dest);
	void (*rebel_pool_color_array_new_copy)(rebel_pool_color_array *r_dest, const rebel_pool_color_array *p_src);
	void (*rebel_pool_color_array_new_with_array)(rebel_pool_color_array *r_dest, const rebel_array *p_a);
	void (*rebel_pool_color_array_append)(rebel_pool_color_array *p_self, const rebel_color *p_data);
	void (*rebel_pool_color_array_append_array)(rebel_pool_color_array *p_self, const rebel_pool_color_array *p_array);
	rebel_error (*rebel_pool_color_array_insert)(rebel_pool_color_array *p_self, const rebel_int p_idx, const rebel_color *p_data);
	void (*rebel_pool_color_array_invert)(rebel_pool_color_array *p_self);
	void (*rebel_pool_color_array_push_back)(rebel_pool_color_array *p_self, const rebel_color *p_data);
	void (*rebel_pool_color_array_remove)(rebel_pool_color_array *p_self, const rebel_int p_idx);
	void (*rebel_pool_color_array_resize)(rebel_pool_color_array *p_self, const rebel_int p_size);
	rebel_pool_color_array_read_access *(*rebel_pool_color_array_read)(const rebel_pool_color_array *p_self);
	rebel_pool_color_array_write_access *(*rebel_pool_color_array_write)(rebel_pool_color_array *p_self);
	void (*rebel_pool_color_array_set)(rebel_pool_color_array *p_self, const rebel_int p_idx, const rebel_color *p_data);
	rebel_color (*rebel_pool_color_array_get)(const rebel_pool_color_array *p_self, const rebel_int p_idx);
	rebel_int (*rebel_pool_color_array_size)(const rebel_pool_color_array *p_self);
	void (*rebel_pool_color_array_destroy)(rebel_pool_color_array *p_self);
	rebel_pool_byte_array_read_access *(*rebel_pool_byte_array_read_access_copy)(const rebel_pool_byte_array_read_access *p_read);
	const uint8_t *(*rebel_pool_byte_array_read_access_ptr)(const rebel_pool_byte_array_read_access *p_read);
	void (*rebel_pool_byte_array_read_access_operator_assign)(rebel_pool_byte_array_read_access *p_read, rebel_pool_byte_array_read_access *p_other);
	void (*rebel_pool_byte_array_read_access_destroy)(rebel_pool_byte_array_read_access *p_read);
	rebel_pool_int_array_read_access *(*rebel_pool_int_array_read_access_copy)(const rebel_pool_int_array_read_access *p_read);
	const rebel_int *(*rebel_pool_int_array_read_access_ptr)(const rebel_pool_int_array_read_access *p_read);
	void (*rebel_pool_int_array_read_access_operator_assign)(rebel_pool_int_array_read_access *p_read, rebel_pool_int_array_read_access *p_other);
	void (*rebel_pool_int_array_read_access_destroy)(rebel_pool_int_array_read_access *p_read);
	rebel_pool_real_array_read_access *(*rebel_pool_real_array_read_access_copy)(const rebel_pool_real_array_read_access *p_read);
	const rebel_real *(*rebel_pool_real_array_read_access_ptr)(const rebel_pool_real_array_read_access *p_read);
	void (*rebel_pool_real_array_read_access_operator_assign)(rebel_pool_real_array_read_access *p_read, rebel_pool_real_array_read_access *p_other);
	void (*rebel_pool_real_array_read_access_destroy)(rebel_pool_real_array_read_access *p_read);
	rebel_pool_string_array_read_access *(*rebel_pool_string_array_read_access_copy)(const rebel_pool_string_array_read_access *p_read);
	const rebel_string *(*rebel_pool_string_array_read_access_ptr)(const rebel_pool_string_array_read_access *p_read);
	void (*rebel_pool_string_array_read_access_operator_assign)(rebel_pool_string_array_read_access *p_read, rebel_pool_string_array_read_access *p_other);
	void (*rebel_pool_string_array_read_access_destroy)(rebel_pool_string_array_read_access *p_read);
	rebel_pool_vector2_array_read_access *(*rebel_pool_vector2_array_read_access_copy)(const rebel_pool_vector2_array_read_access *p_read);
	const rebel_vector2 *(*rebel_pool_vector2_array_read_access_ptr)(const rebel_pool_vector2_array_read_access *p_read);
	void (*rebel_pool_vector2_array_read_access_operator_assign)(rebel_pool_vector2_array_read_access *p_read, rebel_pool_vector2_array_read_access *p_other);
	void (*rebel_pool_vector2_array_read_access_destroy)(rebel_pool_vector2_array_read_access *p_read);
	rebel_pool_vector3_array_read_access *(*rebel_pool_vector3_array_read_access_copy)(const rebel_pool_vector3_array_read_access *p_read);
	const rebel_vector3 *(*rebel_pool_vector3_array_read_access_ptr)(const rebel_pool_vector3_array_read_access *p_read);
	void (*rebel_pool_vector3_array_read_access_operator_assign)(rebel_pool_vector3_array_read_access *p_read, rebel_pool_vector3_array_read_access *p_other);
	void (*rebel_pool_vector3_array_read_access_destroy)(rebel_pool_vector3_array_read_access *p_read);
	rebel_pool_color_array_read_access *(*rebel_pool_color_array_read_access_copy)(const rebel_pool_color_array_read_access *p_read);
	const rebel_color *(*rebel_pool_color_array_read_access_ptr)(const rebel_pool_color_array_read_access *p_read);
	void (*rebel_pool_color_array_read_access_operator_assign)(rebel_pool_color_array_read_access *p_read, rebel_pool_color_array_read_access *p_other);
	void (*rebel_pool_color_array_read_access_destroy)(rebel_pool_color_array_read_access *p_read);
	rebel_pool_byte_array_write_access *(*rebel_pool_byte_array_write_access_copy)(const rebel_pool_byte_array_write_access *p_write);
	uint8_t *(*rebel_pool_byte_array_write_access_ptr)(const rebel_pool_byte_array_write_access *p_write);
	void (*rebel_pool_byte_array_write_access_operator_assign)(rebel_pool_byte_array_write_access *p_write, rebel_pool_byte_array_write_access *p_other);
	void (*rebel_pool_byte_array_write_access_destroy)(rebel_pool_byte_array_write_access *p_write);
	rebel_pool_int_array_write_access *(*rebel_pool_int_array_write_access_copy)(const rebel_pool_int_array_write_access *p_write);
	rebel_int *(*rebel_pool_int_array_write_access_ptr)(const rebel_pool_int_array_write_access *p_write);
	void (*rebel_pool_int_array_write_access_operator_assign)(rebel_pool_int_array_write_access *p_write, rebel_pool_int_array_write_access *p_other);
	void (*rebel_pool_int_array_write_access_destroy)(rebel_pool_int_array_write_access *p_write);
	rebel_pool_real_array_write_access *(*rebel_pool_real_array_write_access_copy)(const rebel_pool_real_array_write_access *p_write);
	rebel_real *(*rebel_pool_real_array_write_access_ptr)(const rebel_pool_real_array_write_access *p_write);
	void (*rebel_pool_real_array_write_access_operator_assign)(rebel_pool_real_array_write_access *p_write, rebel_pool_real_array_write_access *p_other);
	void (*rebel_pool_real_array_write_access_destroy)(rebel_pool_real_array_write_access *p_write);
	rebel_pool_string_array_write_access *(*rebel_pool_string_array_write_access_copy)(const rebel_pool_string_array_write_access *p_write);
	rebel_string *(*rebel_pool_string_array_write_access_ptr)(const rebel_pool_string_array_write_access *p_write);
	void (*rebel_pool_string_array_write_access_operator_assign)(rebel_pool_string_array_write_access *p_write, rebel_pool_string_array_write_access *p_other);
	void (*rebel_pool_string_array_write_access_destroy)(rebel_pool_string_array_write_access *p_write);
	rebel_pool_vector2_array_write_access *(*rebel_pool_vector2_array_write_access_copy)(const rebel_pool_vector2_array_write_access *p_write);
	rebel_vector2 *(*rebel_pool_vector2_array_write_access_ptr)(const rebel_pool_vector2_array_write_access *p_write);
	void (*rebel_pool_vector2_array_write_access_operator_assign)(rebel_pool_vector2_array_write_access *p_write, rebel_pool_vector2_array_write_access *p_other);
	void (*rebel_pool_vector2_array_write_access_destroy)(rebel_pool_vector2_array_write_access *p_write);
	rebel_pool_vector3_array_write_access *(*rebel_pool_vector3_array_write_access_copy)(const rebel_pool_vector3_array_write_access *p_write);
	rebel_vector3 *(*rebel_pool_vector3_array_write_access_ptr)(const rebel_pool_vector3_array_write_access *p_write);
	void (*rebel_pool_vector3_array_write_access_operator_assign)(rebel_pool_vector3_array_write_access *p_write, rebel_pool_vector3_array_write_access *p_other);
	void (*rebel_pool_vector3_array_write_access_destroy)(rebel_pool_vector3_array_write_access *p_write);
	rebel_pool_color_array_write_access *(*rebel_pool_color_array_write_access_copy)(const rebel_pool_color_array_write_access *p_write);
	rebel_color *(*rebel_pool_color_array_write_access_ptr)(const rebel_pool_color_array_write_access *p_write);
	void (*rebel_pool_color_array_write_access_operator_assign)(rebel_pool_color_array_write_access *p_write, rebel_pool_color_array_write_access *p_other);
	void (*rebel_pool_color_array_write_access_destroy)(rebel_pool_color_array_write_access *p_write);
	void (*rebel_array_new)(rebel_array *r_dest);
	void (*rebel_array_new_copy)(rebel_array *r_dest, const rebel_array *p_src);
	void (*rebel_array_new_pool_color_array)(rebel_array *r_dest, const rebel_pool_color_array *p_pca);
	void (*rebel_array_new_pool_vector3_array)(rebel_array *r_dest, const rebel_pool_vector3_array *p_pv3a);
	void (*rebel_array_new_pool_vector2_array)(rebel_array *r_dest, const rebel_pool_vector2_array *p_pv2a);
	void (*rebel_array_new_pool_string_array)(rebel_array *r_dest, const rebel_pool_string_array *p_psa);
	void (*rebel_array_new_pool_real_array)(rebel_array *r_dest, const rebel_pool_real_array *p_pra);
	void (*rebel_array_new_pool_int_array)(rebel_array *r_dest, const rebel_pool_int_array *p_pia);
	void (*rebel_array_new_pool_byte_array)(rebel_array *r_dest, const rebel_pool_byte_array *p_pba);
	void (*rebel_array_set)(rebel_array *p_self, const rebel_int p_idx, const rebel_variant *p_value);
	rebel_variant (*rebel_array_get)(const rebel_array *p_self, const rebel_int p_idx);
	rebel_variant *(*rebel_array_operator_index)(rebel_array *p_self, const rebel_int p_idx);
	const rebel_variant *(*rebel_array_operator_index_const)(const rebel_array *p_self, const rebel_int p_idx);
	void (*rebel_array_append)(rebel_array *p_self, const rebel_variant *p_value);
	void (*rebel_array_clear)(rebel_array *p_self);
	rebel_int (*rebel_array_count)(const rebel_array *p_self, const rebel_variant *p_value);
	rebel_bool (*rebel_array_empty)(const rebel_array *p_self);
	void (*rebel_array_erase)(rebel_array *p_self, const rebel_variant *p_value);
	rebel_variant (*rebel_array_front)(const rebel_array *p_self);
	rebel_variant (*rebel_array_back)(const rebel_array *p_self);
	rebel_int (*rebel_array_find)(const rebel_array *p_self, const rebel_variant *p_what, const rebel_int p_from);
	rebel_int (*rebel_array_find_last)(const rebel_array *p_self, const rebel_variant *p_what);
	rebel_bool (*rebel_array_has)(const rebel_array *p_self, const rebel_variant *p_value);
	rebel_int (*rebel_array_hash)(const rebel_array *p_self);
	void (*rebel_array_insert)(rebel_array *p_self, const rebel_int p_pos, const rebel_variant *p_value);
	void (*rebel_array_invert)(rebel_array *p_self);
	rebel_variant (*rebel_array_pop_back)(rebel_array *p_self);
	rebel_variant (*rebel_array_pop_front)(rebel_array *p_self);
	void (*rebel_array_push_back)(rebel_array *p_self, const rebel_variant *p_value);
	void (*rebel_array_push_front)(rebel_array *p_self, const rebel_variant *p_value);
	void (*rebel_array_remove)(rebel_array *p_self, const rebel_int p_idx);
	void (*rebel_array_resize)(rebel_array *p_self, const rebel_int p_size);
	rebel_int (*rebel_array_rfind)(const rebel_array *p_self, const rebel_variant *p_what, const rebel_int p_from);
	rebel_int (*rebel_array_size)(const rebel_array *p_self);
	void (*rebel_array_sort)(rebel_array *p_self);
	void (*rebel_array_sort_custom)(rebel_array *p_self, rebel_object *p_obj, const rebel_string *p_func);
	rebel_int (*rebel_array_bsearch)(rebel_array *p_self, const rebel_variant *p_value, const rebel_bool p_before);
	rebel_int (*rebel_array_bsearch_custom)(rebel_array *p_self, const rebel_variant *p_value, rebel_object *p_obj, const rebel_string *p_func, const rebel_bool p_before);
	void (*rebel_array_destroy)(rebel_array *p_self);
	void (*rebel_dictionary_new)(rebel_dictionary *r_dest);
	void (*rebel_dictionary_new_copy)(rebel_dictionary *r_dest, const rebel_dictionary *p_src);
	void (*rebel_dictionary_destroy)(rebel_dictionary *p_self);
	rebel_int (*rebel_dictionary_size)(const rebel_dictionary *p_self);
	rebel_bool (*rebel_dictionary_empty)(const rebel_dictionary *p_self);
	void (*rebel_dictionary_clear)(rebel_dictionary *p_self);
	rebel_bool (*rebel_dictionary_has)(const rebel_dictionary *p_self, const rebel_variant *p_key);
	rebel_bool (*rebel_dictionary_has_all)(const rebel_dictionary *p_self, const rebel_array *p_keys);
	void (*rebel_dictionary_erase)(rebel_dictionary *p_self, const rebel_variant *p_key);
	rebel_int (*rebel_dictionary_hash)(const rebel_dictionary *p_self);
	rebel_array (*rebel_dictionary_keys)(const rebel_dictionary *p_self);
	rebel_array (*rebel_dictionary_values)(const rebel_dictionary *p_self);
	rebel_variant (*rebel_dictionary_get)(const rebel_dictionary *p_self, const rebel_variant *p_key);
	void (*rebel_dictionary_set)(rebel_dictionary *p_self, const rebel_variant *p_key, const rebel_variant *p_value);
	rebel_variant *(*rebel_dictionary_operator_index)(rebel_dictionary *p_self, const rebel_variant *p_key);
	const rebel_variant *(*rebel_dictionary_operator_index_const)(const rebel_dictionary *p_self, const rebel_variant *p_key);
	rebel_variant *(*rebel_dictionary_next)(const rebel_dictionary *p_self, const rebel_variant *p_key);
	rebel_bool (*rebel_dictionary_operator_equal)(const rebel_dictionary *p_self, const rebel_dictionary *p_b);
	rebel_string (*rebel_dictionary_to_json)(const rebel_dictionary *p_self);
	void (*rebel_node_path_new)(rebel_node_path *r_dest, const rebel_string *p_from);
	void (*rebel_node_path_new_copy)(rebel_node_path *r_dest, const rebel_node_path *p_src);
	void (*rebel_node_path_destroy)(rebel_node_path *p_self);
	rebel_string (*rebel_node_path_as_string)(const rebel_node_path *p_self);
	rebel_bool (*rebel_node_path_is_absolute)(const rebel_node_path *p_self);
	rebel_int (*rebel_node_path_get_name_count)(const rebel_node_path *p_self);
	rebel_string (*rebel_node_path_get_name)(const rebel_node_path *p_self, const rebel_int p_idx);
	rebel_int (*rebel_node_path_get_subname_count)(const rebel_node_path *p_self);
	rebel_string (*rebel_node_path_get_subname)(const rebel_node_path *p_self, const rebel_int p_idx);
	rebel_string (*rebel_node_path_get_concatenated_subnames)(const rebel_node_path *p_self);
	rebel_bool (*rebel_node_path_is_empty)(const rebel_node_path *p_self);
	rebel_bool (*rebel_node_path_operator_equal)(const rebel_node_path *p_self, const rebel_node_path *p_b);
	void (*rebel_plane_new_with_reals)(rebel_plane *r_dest, const rebel_real p_a, const rebel_real p_b, const rebel_real p_c, const rebel_real p_d);
	void (*rebel_plane_new_with_vectors)(rebel_plane *r_dest, const rebel_vector3 *p_v1, const rebel_vector3 *p_v2, const rebel_vector3 *p_v3);
	void (*rebel_plane_new_with_normal)(rebel_plane *r_dest, const rebel_vector3 *p_normal, const rebel_real p_d);
	rebel_string (*rebel_plane_as_string)(const rebel_plane *p_self);
	rebel_plane (*rebel_plane_normalized)(const rebel_plane *p_self);
	rebel_vector3 (*rebel_plane_center)(const rebel_plane *p_self);
	rebel_vector3 (*rebel_plane_get_any_point)(const rebel_plane *p_self);
	rebel_bool (*rebel_plane_is_point_over)(const rebel_plane *p_self, const rebel_vector3 *p_point);
	rebel_real (*rebel_plane_distance_to)(const rebel_plane *p_self, const rebel_vector3 *p_point);
	rebel_bool (*rebel_plane_has_point)(const rebel_plane *p_self, const rebel_vector3 *p_point, const rebel_real p_epsilon);
	rebel_vector3 (*rebel_plane_project)(const rebel_plane *p_self, const rebel_vector3 *p_point);
	rebel_bool (*rebel_plane_intersect_3)(const rebel_plane *p_self, rebel_vector3 *r_dest, const rebel_plane *p_b, const rebel_plane *p_c);
	rebel_bool (*rebel_plane_intersects_ray)(const rebel_plane *p_self, rebel_vector3 *r_dest, const rebel_vector3 *p_from, const rebel_vector3 *p_dir);
	rebel_bool (*rebel_plane_intersects_segment)(const rebel_plane *p_self, rebel_vector3 *r_dest, const rebel_vector3 *p_begin, const rebel_vector3 *p_end);
	rebel_plane (*rebel_plane_operator_neg)(const rebel_plane *p_self);
	rebel_bool (*rebel_plane_operator_equal)(const rebel_plane *p_self, const rebel_plane *p_b);
	void (*rebel_plane_set_normal)(rebel_plane *p_self, const rebel_vector3 *p_normal);
	rebel_vector3 (*rebel_plane_get_normal)(const rebel_plane *p_self);
	rebel_real (*rebel_plane_get_d)(const rebel_plane *p_self);
	void (*rebel_plane_set_d)(rebel_plane *p_self, const rebel_real p_d);
	void (*rebel_rect2_new_with_position_and_size)(rebel_rect2 *r_dest, const rebel_vector2 *p_pos, const rebel_vector2 *p_size);
	void (*rebel_rect2_new)(rebel_rect2 *r_dest, const rebel_real p_x, const rebel_real p_y, const rebel_real p_width, const rebel_real p_height);
	rebel_string (*rebel_rect2_as_string)(const rebel_rect2 *p_self);
	rebel_real (*rebel_rect2_get_area)(const rebel_rect2 *p_self);
	rebel_bool (*rebel_rect2_intersects)(const rebel_rect2 *p_self, const rebel_rect2 *p_b);
	rebel_bool (*rebel_rect2_encloses)(const rebel_rect2 *p_self, const rebel_rect2 *p_b);
	rebel_bool (*rebel_rect2_has_no_area)(const rebel_rect2 *p_self);
	rebel_rect2 (*rebel_rect2_clip)(const rebel_rect2 *p_self, const rebel_rect2 *p_b);
	rebel_rect2 (*rebel_rect2_merge)(const rebel_rect2 *p_self, const rebel_rect2 *p_b);
	rebel_bool (*rebel_rect2_has_point)(const rebel_rect2 *p_self, const rebel_vector2 *p_point);
	rebel_rect2 (*rebel_rect2_grow)(const rebel_rect2 *p_self, const rebel_real p_by);
	rebel_rect2 (*rebel_rect2_expand)(const rebel_rect2 *p_self, const rebel_vector2 *p_to);
	rebel_bool (*rebel_rect2_operator_equal)(const rebel_rect2 *p_self, const rebel_rect2 *p_b);
	rebel_vector2 (*rebel_rect2_get_position)(const rebel_rect2 *p_self);
	rebel_vector2 (*rebel_rect2_get_size)(const rebel_rect2 *p_self);
	void (*rebel_rect2_set_position)(rebel_rect2 *p_self, const rebel_vector2 *p_pos);
	void (*rebel_rect2_set_size)(rebel_rect2 *p_self, const rebel_vector2 *p_size);
	void (*rebel_aabb_new)(rebel_aabb *r_dest, const rebel_vector3 *p_pos, const rebel_vector3 *p_size);
	rebel_vector3 (*rebel_aabb_get_position)(const rebel_aabb *p_self);
	void (*rebel_aabb_set_position)(const rebel_aabb *p_self, const rebel_vector3 *p_v);
	rebel_vector3 (*rebel_aabb_get_size)(const rebel_aabb *p_self);
	void (*rebel_aabb_set_size)(const rebel_aabb *p_self, const rebel_vector3 *p_v);
	rebel_string (*rebel_aabb_as_string)(const rebel_aabb *p_self);
	rebel_real (*rebel_aabb_get_area)(const rebel_aabb *p_self);
	rebel_bool (*rebel_aabb_has_no_area)(const rebel_aabb *p_self);
	rebel_bool (*rebel_aabb_has_no_surface)(const rebel_aabb *p_self);
	rebel_bool (*rebel_aabb_intersects)(const rebel_aabb *p_self, const rebel_aabb *p_with);
	rebel_bool (*rebel_aabb_encloses)(const rebel_aabb *p_self, const rebel_aabb *p_with);
	rebel_aabb (*rebel_aabb_merge)(const rebel_aabb *p_self, const rebel_aabb *p_with);
	rebel_aabb (*rebel_aabb_intersection)(const rebel_aabb *p_self, const rebel_aabb *p_with);
	rebel_bool (*rebel_aabb_intersects_plane)(const rebel_aabb *p_self, const rebel_plane *p_plane);
	rebel_bool (*rebel_aabb_intersects_segment)(const rebel_aabb *p_self, const rebel_vector3 *p_from, const rebel_vector3 *p_to);
	rebel_bool (*rebel_aabb_has_point)(const rebel_aabb *p_self, const rebel_vector3 *p_point);
	rebel_vector3 (*rebel_aabb_get_support)(const rebel_aabb *p_self, const rebel_vector3 *p_dir);
	rebel_vector3 (*rebel_aabb_get_longest_axis)(const rebel_aabb *p_self);
	rebel_int (*rebel_aabb_get_longest_axis_index)(const rebel_aabb *p_self);
	rebel_real (*rebel_aabb_get_longest_axis_size)(const rebel_aabb *p_self);
	rebel_vector3 (*rebel_aabb_get_shortest_axis)(const rebel_aabb *p_self);
	rebel_int (*rebel_aabb_get_shortest_axis_index)(const rebel_aabb *p_self);
	rebel_real (*rebel_aabb_get_shortest_axis_size)(const rebel_aabb *p_self);
	rebel_aabb (*rebel_aabb_expand)(const rebel_aabb *p_self, const rebel_vector3 *p_to_point);
	rebel_aabb (*rebel_aabb_grow)(const rebel_aabb *p_self, const rebel_real p_by);
	rebel_vector3 (*rebel_aabb_get_endpoint)(const rebel_aabb *p_self, const rebel_int p_idx);
	rebel_bool (*rebel_aabb_operator_equal)(const rebel_aabb *p_self, const rebel_aabb *p_b);
	void (*rebel_rid_new)(rebel_rid *r_dest);
	rebel_int (*rebel_rid_get_id)(const rebel_rid *p_self);
	void (*rebel_rid_new_with_resource)(rebel_rid *r_dest, const rebel_object *p_from);
	rebel_bool (*rebel_rid_operator_equal)(const rebel_rid *p_self, const rebel_rid *p_b);
	rebel_bool (*rebel_rid_operator_less)(const rebel_rid *p_self, const rebel_rid *p_b);
	void (*rebel_transform_new_with_axis_origin)(rebel_transform *r_dest, const rebel_vector3 *p_x_axis, const rebel_vector3 *p_y_axis, const rebel_vector3 *p_z_axis, const rebel_vector3 *p_origin);
	void (*rebel_transform_new)(rebel_transform *r_dest, const rebel_basis *p_basis, const rebel_vector3 *p_origin);
	rebel_basis (*rebel_transform_get_basis)(const rebel_transform *p_self);
	void (*rebel_transform_set_basis)(rebel_transform *p_self, const rebel_basis *p_v);
	rebel_vector3 (*rebel_transform_get_origin)(const rebel_transform *p_self);
	void (*rebel_transform_set_origin)(rebel_transform *p_self, const rebel_vector3 *p_v);
	rebel_string (*rebel_transform_as_string)(const rebel_transform *p_self);
	rebel_transform (*rebel_transform_inverse)(const rebel_transform *p_self);
	rebel_transform (*rebel_transform_affine_inverse)(const rebel_transform *p_self);
	rebel_transform (*rebel_transform_orthonormalized)(const rebel_transform *p_self);
	rebel_transform (*rebel_transform_rotated)(const rebel_transform *p_self, const rebel_vector3 *p_axis, const rebel_real p_phi);
	rebel_transform (*rebel_transform_scaled)(const rebel_transform *p_self, const rebel_vector3 *p_scale);
	rebel_transform (*rebel_transform_translated)(const rebel_transform *p_self, const rebel_vector3 *p_ofs);
	rebel_transform (*rebel_transform_looking_at)(const rebel_transform *p_self, const rebel_vector3 *p_target, const rebel_vector3 *p_up);
	rebel_plane (*rebel_transform_xform_plane)(const rebel_transform *p_self, const rebel_plane *p_v);
	rebel_plane (*rebel_transform_xform_inv_plane)(const rebel_transform *p_self, const rebel_plane *p_v);
	void (*rebel_transform_new_identity)(rebel_transform *r_dest);
	rebel_bool (*rebel_transform_operator_equal)(const rebel_transform *p_self, const rebel_transform *p_b);
	rebel_transform (*rebel_transform_operator_multiply)(const rebel_transform *p_self, const rebel_transform *p_b);
	rebel_vector3 (*rebel_transform_xform_vector3)(const rebel_transform *p_self, const rebel_vector3 *p_v);
	rebel_vector3 (*rebel_transform_xform_inv_vector3)(const rebel_transform *p_self, const rebel_vector3 *p_v);
	rebel_aabb (*rebel_transform_xform_aabb)(const rebel_transform *p_self, const rebel_aabb *p_v);
	rebel_aabb (*rebel_transform_xform_inv_aabb)(const rebel_transform *p_self, const rebel_aabb *p_v);
	void (*rebel_transform2d_new)(rebel_transform2d *r_dest, const rebel_real p_rot, const rebel_vector2 *p_pos);
	void (*rebel_transform2d_new_axis_origin)(rebel_transform2d *r_dest, const rebel_vector2 *p_x_axis, const rebel_vector2 *p_y_axis, const rebel_vector2 *p_origin);
	rebel_string (*rebel_transform2d_as_string)(const rebel_transform2d *p_self);
	rebel_transform2d (*rebel_transform2d_inverse)(const rebel_transform2d *p_self);
	rebel_transform2d (*rebel_transform2d_affine_inverse)(const rebel_transform2d *p_self);
	rebel_real (*rebel_transform2d_get_rotation)(const rebel_transform2d *p_self);
	rebel_vector2 (*rebel_transform2d_get_origin)(const rebel_transform2d *p_self);
	rebel_vector2 (*rebel_transform2d_get_scale)(const rebel_transform2d *p_self);
	rebel_transform2d (*rebel_transform2d_orthonormalized)(const rebel_transform2d *p_self);
	rebel_transform2d (*rebel_transform2d_rotated)(const rebel_transform2d *p_self, const rebel_real p_phi);
	rebel_transform2d (*rebel_transform2d_scaled)(const rebel_transform2d *p_self, const rebel_vector2 *p_scale);
	rebel_transform2d (*rebel_transform2d_translated)(const rebel_transform2d *p_self, const rebel_vector2 *p_offset);
	rebel_vector2 (*rebel_transform2d_xform_vector2)(const rebel_transform2d *p_self, const rebel_vector2 *p_v);
	rebel_vector2 (*rebel_transform2d_xform_inv_vector2)(const rebel_transform2d *p_self, const rebel_vector2 *p_v);
	rebel_vector2 (*rebel_transform2d_basis_xform_vector2)(const rebel_transform2d *p_self, const rebel_vector2 *p_v);
	rebel_vector2 (*rebel_transform2d_basis_xform_inv_vector2)(const rebel_transform2d *p_self, const rebel_vector2 *p_v);
	rebel_transform2d (*rebel_transform2d_interpolate_with)(const rebel_transform2d *p_self, const rebel_transform2d *p_m, const rebel_real p_c);
	rebel_bool (*rebel_transform2d_operator_equal)(const rebel_transform2d *p_self, const rebel_transform2d *p_b);
	rebel_transform2d (*rebel_transform2d_operator_multiply)(const rebel_transform2d *p_self, const rebel_transform2d *p_b);
	void (*rebel_transform2d_new_identity)(rebel_transform2d *r_dest);
	rebel_rect2 (*rebel_transform2d_xform_rect2)(const rebel_transform2d *p_self, const rebel_rect2 *p_v);
	rebel_rect2 (*rebel_transform2d_xform_inv_rect2)(const rebel_transform2d *p_self, const rebel_rect2 *p_v);
	rebel_variant_type (*rebel_variant_get_type)(const rebel_variant *p_v);
	void (*rebel_variant_new_copy)(rebel_variant *r_dest, const rebel_variant *p_src);
	void (*rebel_variant_new_nil)(rebel_variant *r_dest);
	void (*rebel_variant_new_bool)(rebel_variant *r_dest, const rebel_bool p_b);
	void (*rebel_variant_new_uint)(rebel_variant *r_dest, const uint64_t p_i);
	void (*rebel_variant_new_int)(rebel_variant *r_dest, const int64_t p_i);
	void (*rebel_variant_new_real)(rebel_variant *r_dest, const double p_r);
	void (*rebel_variant_new_string)(rebel_variant *r_dest, const rebel_string *p_s);
	void (*rebel_variant_new_vector2)(rebel_variant *r_dest, const rebel_vector2 *p_v2);
	void (*rebel_variant_new_rect2)(rebel_variant *r_dest, const rebel_rect2 *p_rect2);
	void (*rebel_variant_new_vector3)(rebel_variant *r_dest, const rebel_vector3 *p_v3);
	void (*rebel_variant_new_transform2d)(rebel_variant *r_dest, const rebel_transform2d *p_t2d);
	void (*rebel_variant_new_plane)(rebel_variant *r_dest, const rebel_plane *p_plane);
	void (*rebel_variant_new_quat)(rebel_variant *r_dest, const rebel_quat *p_quat);
	void (*rebel_variant_new_aabb)(rebel_variant *r_dest, const rebel_aabb *p_aabb);
	void (*rebel_variant_new_basis)(rebel_variant *r_dest, const rebel_basis *p_basis);
	void (*rebel_variant_new_transform)(rebel_variant *r_dest, const rebel_transform *p_trans);
	void (*rebel_variant_new_color)(rebel_variant *r_dest, const rebel_color *p_color);
	void (*rebel_variant_new_node_path)(rebel_variant *r_dest, const rebel_node_path *p_np);
	void (*rebel_variant_new_rid)(rebel_variant *r_dest, const rebel_rid *p_rid);
	void (*rebel_variant_new_object)(rebel_variant *r_dest, const rebel_object *p_obj);
	void (*rebel_variant_new_dictionary)(rebel_variant *r_dest, const rebel_dictionary *p_dict);
	void (*rebel_variant_new_array)(rebel_variant *r_dest, const rebel_array *p_arr);
	void (*rebel_variant_new_pool_byte_array)(rebel_variant *r_dest, const rebel_pool_byte_array *p_pba);
	void (*rebel_variant_new_pool_int_array)(rebel_variant *r_dest, const rebel_pool_int_array *p_pia);
	void (*rebel_variant_new_pool_real_array)(rebel_variant *r_dest, const rebel_pool_real_array *p_pra);
	void (*rebel_variant_new_pool_string_array)(rebel_variant *r_dest, const rebel_pool_string_array *p_psa);
	void (*rebel_variant_new_pool_vector2_array)(rebel_variant *r_dest, const rebel_pool_vector2_array *p_pv2a);
	void (*rebel_variant_new_pool_vector3_array)(rebel_variant *r_dest, const rebel_pool_vector3_array *p_pv3a);
	void (*rebel_variant_new_pool_color_array)(rebel_variant *r_dest, const rebel_pool_color_array *p_pca);
	rebel_bool (*rebel_variant_as_bool)(const rebel_variant *p_self);
	uint64_t (*rebel_variant_as_uint)(const rebel_variant *p_self);
	int64_t (*rebel_variant_as_int)(const rebel_variant *p_self);
	double (*rebel_variant_as_real)(const rebel_variant *p_self);
	rebel_string (*rebel_variant_as_string)(const rebel_variant *p_self);
	rebel_vector2 (*rebel_variant_as_vector2)(const rebel_variant *p_self);
	rebel_rect2 (*rebel_variant_as_rect2)(const rebel_variant *p_self);
	rebel_vector3 (*rebel_variant_as_vector3)(const rebel_variant *p_self);
	rebel_transform2d (*rebel_variant_as_transform2d)(const rebel_variant *p_self);
	rebel_plane (*rebel_variant_as_plane)(const rebel_variant *p_self);
	rebel_quat (*rebel_variant_as_quat)(const rebel_variant *p_self);
	rebel_aabb (*rebel_variant_as_aabb)(const rebel_variant *p_self);
	rebel_basis (*rebel_variant_as_basis)(const rebel_variant *p_self);
	rebel_transform (*rebel_variant_as_transform)(const rebel_variant *p_self);
	rebel_color (*rebel_variant_as_color)(const rebel_variant *p_self);
	rebel_node_path (*rebel_variant_as_node_path)(const rebel_variant *p_self);
	rebel_rid (*rebel_variant_as_rid)(const rebel_variant *p_self);
	rebel_object *(*rebel_variant_as_object)(const rebel_variant *p_self);
	rebel_dictionary (*rebel_variant_as_dictionary)(const rebel_variant *p_self);
	rebel_array (*rebel_variant_as_array)(const rebel_variant *p_self);
	rebel_pool_byte_array (*rebel_variant_as_pool_byte_array)(const rebel_variant *p_self);
	rebel_pool_int_array (*rebel_variant_as_pool_int_array)(const rebel_variant *p_self);
	rebel_pool_real_array (*rebel_variant_as_pool_real_array)(const rebel_variant *p_self);
	rebel_pool_string_array (*rebel_variant_as_pool_string_array)(const rebel_variant *p_self);
	rebel_pool_vector2_array (*rebel_variant_as_pool_vector2_array)(const rebel_variant *p_self);
	rebel_pool_vector3_array (*rebel_variant_as_pool_vector3_array)(const rebel_variant *p_self);
	rebel_pool_color_array (*rebel_variant_as_pool_color_array)(const rebel_variant *p_self);
	rebel_variant (*rebel_variant_call)(rebel_variant *p_self, const rebel_string *p_method, const rebel_variant **p_args, const rebel_int p_argcount, rebel_variant_call_error *r_error);
	rebel_bool (*rebel_variant_has_method)(const rebel_variant *p_self, const rebel_string *p_method);
	rebel_bool (*rebel_variant_operator_equal)(const rebel_variant *p_self, const rebel_variant *p_other);
	rebel_bool (*rebel_variant_operator_less)(const rebel_variant *p_self, const rebel_variant *p_other);
	rebel_bool (*rebel_variant_hash_compare)(const rebel_variant *p_self, const rebel_variant *p_other);
	rebel_bool (*rebel_variant_booleanize)(const rebel_variant *p_self);
	void (*rebel_variant_destroy)(rebel_variant *p_self);
	rebel_int (*rebel_char_string_length)(const rebel_char_string *p_cs);
	const char *(*rebel_char_string_get_data)(const rebel_char_string *p_cs);
	void (*rebel_char_string_destroy)(rebel_char_string *p_cs);
	void (*rebel_string_new)(rebel_string *r_dest);
	void (*rebel_string_new_copy)(rebel_string *r_dest, const rebel_string *p_src);
	void (*rebel_string_new_with_wide_string)(rebel_string *r_dest, const wchar_t *p_contents, const int p_size);
	const wchar_t *(*rebel_string_operator_index)(rebel_string *p_self, const rebel_int p_idx);
	wchar_t (*rebel_string_operator_index_const)(const rebel_string *p_self, const rebel_int p_idx);
	const wchar_t *(*rebel_string_wide_str)(const rebel_string *p_self);
	rebel_bool (*rebel_string_operator_equal)(const rebel_string *p_self, const rebel_string *p_b);
	rebel_bool (*rebel_string_operator_less)(const rebel_string *p_self, const rebel_string *p_b);
	rebel_string (*rebel_string_operator_plus)(const rebel_string *p_self, const rebel_string *p_b);
	rebel_int (*rebel_string_length)(const rebel_string *p_self);
	signed char (*rebel_string_casecmp_to)(const rebel_string *p_self, const rebel_string *p_str);
	signed char (*rebel_string_nocasecmp_to)(const rebel_string *p_self, const rebel_string *p_str);
	signed char (*rebel_string_naturalnocasecmp_to)(const rebel_string *p_self, const rebel_string *p_str);
	rebel_bool (*rebel_string_begins_with)(const rebel_string *p_self, const rebel_string *p_string);
	rebel_bool (*rebel_string_begins_with_char_array)(const rebel_string *p_self, const char *p_char_array);
	rebel_array (*rebel_string_bigrams)(const rebel_string *p_self);
	rebel_string (*rebel_string_chr)(wchar_t p_character);
	rebel_bool (*rebel_string_ends_with)(const rebel_string *p_self, const rebel_string *p_string);
	rebel_int (*rebel_string_find)(const rebel_string *p_self, rebel_string p_what);
	rebel_int (*rebel_string_find_from)(const rebel_string *p_self, rebel_string p_what, rebel_int p_from);
	rebel_int (*rebel_string_findmk)(const rebel_string *p_self, const rebel_array *p_keys);
	rebel_int (*rebel_string_findmk_from)(const rebel_string *p_self, const rebel_array *p_keys, rebel_int p_from);
	rebel_int (*rebel_string_findmk_from_in_place)(const rebel_string *p_self, const rebel_array *p_keys, rebel_int p_from, rebel_int *r_key);
	rebel_int (*rebel_string_findn)(const rebel_string *p_self, rebel_string p_what);
	rebel_int (*rebel_string_findn_from)(const rebel_string *p_self, rebel_string p_what, rebel_int p_from);
	rebel_int (*rebel_string_find_last)(const rebel_string *p_self, rebel_string p_what);
	rebel_string (*rebel_string_format)(const rebel_string *p_self, const rebel_variant *p_values);
	rebel_string (*rebel_string_format_with_custom_placeholder)(const rebel_string *p_self, const rebel_variant *p_values, const char *p_placeholder);
	rebel_string (*rebel_string_hex_encode_buffer)(const uint8_t *p_buffer, rebel_int p_len);
	rebel_int (*rebel_string_hex_to_int)(const rebel_string *p_self);
	rebel_int (*rebel_string_hex_to_int_without_prefix)(const rebel_string *p_self);
	rebel_string (*rebel_string_insert)(const rebel_string *p_self, rebel_int p_at_pos, rebel_string p_string);
	rebel_bool (*rebel_string_is_numeric)(const rebel_string *p_self);
	rebel_bool (*rebel_string_is_subsequence_of)(const rebel_string *p_self, const rebel_string *p_string);
	rebel_bool (*rebel_string_is_subsequence_ofi)(const rebel_string *p_self, const rebel_string *p_string);
	rebel_string (*rebel_string_lpad)(const rebel_string *p_self, rebel_int p_min_length);
	rebel_string (*rebel_string_lpad_with_custom_character)(const rebel_string *p_self, rebel_int p_min_length, const rebel_string *p_character);
	rebel_bool (*rebel_string_match)(const rebel_string *p_self, const rebel_string *p_wildcard);
	rebel_bool (*rebel_string_matchn)(const rebel_string *p_self, const rebel_string *p_wildcard);
	rebel_string (*rebel_string_md5)(const uint8_t *p_md5);
	rebel_string (*rebel_string_num)(double p_num);
	rebel_string (*rebel_string_num_int64)(int64_t p_num, rebel_int p_base);
	rebel_string (*rebel_string_num_int64_capitalized)(int64_t p_num, rebel_int p_base, rebel_bool p_capitalize_hex);
	rebel_string (*rebel_string_num_real)(double p_num);
	rebel_string (*rebel_string_num_scientific)(double p_num);
	rebel_string (*rebel_string_num_with_decimals)(double p_num, rebel_int p_decimals);
	rebel_string (*rebel_string_pad_decimals)(const rebel_string *p_self, rebel_int p_digits);
	rebel_string (*rebel_string_pad_zeros)(const rebel_string *p_self, rebel_int p_digits);
	rebel_string (*rebel_string_replace_first)(const rebel_string *p_self, rebel_string p_key, rebel_string p_with);
	rebel_string (*rebel_string_replace)(const rebel_string *p_self, rebel_string p_key, rebel_string p_with);
	rebel_string (*rebel_string_replacen)(const rebel_string *p_self, rebel_string p_key, rebel_string p_with);
	rebel_int (*rebel_string_rfind)(const rebel_string *p_self, rebel_string p_what);
	rebel_int (*rebel_string_rfindn)(const rebel_string *p_self, rebel_string p_what);
	rebel_int (*rebel_string_rfind_from)(const rebel_string *p_self, rebel_string p_what, rebel_int p_from);
	rebel_int (*rebel_string_rfindn_from)(const rebel_string *p_self, rebel_string p_what, rebel_int p_from);
	rebel_string (*rebel_string_rpad)(const rebel_string *p_self, rebel_int p_min_length);
	rebel_string (*rebel_string_rpad_with_custom_character)(const rebel_string *p_self, rebel_int p_min_length, const rebel_string *p_character);
	rebel_real (*rebel_string_similarity)(const rebel_string *p_self, const rebel_string *p_string);
	rebel_string (*rebel_string_sprintf)(const rebel_string *p_self, const rebel_array *p_values, rebel_bool *p_error);
	rebel_string (*rebel_string_substr)(const rebel_string *p_self, rebel_int p_from, rebel_int p_chars);
	double (*rebel_string_to_double)(const rebel_string *p_self);
	rebel_real (*rebel_string_to_float)(const rebel_string *p_self);
	rebel_int (*rebel_string_to_int)(const rebel_string *p_self);
	rebel_string (*rebel_string_camelcase_to_underscore)(const rebel_string *p_self);
	rebel_string (*rebel_string_camelcase_to_underscore_lowercased)(const rebel_string *p_self);
	rebel_string (*rebel_string_capitalize)(const rebel_string *p_self);
	double (*rebel_string_char_to_double)(const char *p_what);
	rebel_int (*rebel_string_char_to_int)(const char *p_what);
	int64_t (*rebel_string_wchar_to_int)(const wchar_t *p_str);
	rebel_int (*rebel_string_char_to_int_with_len)(const char *p_what, rebel_int p_len);
	int64_t (*rebel_string_char_to_int64_with_len)(const wchar_t *p_str, int p_len);
	int64_t (*rebel_string_hex_to_int64)(const rebel_string *p_self);
	int64_t (*rebel_string_hex_to_int64_with_prefix)(const rebel_string *p_self);
	int64_t (*rebel_string_to_int64)(const rebel_string *p_self);
	double (*rebel_string_unicode_char_to_double)(const wchar_t *p_str, const wchar_t **r_end);
	rebel_int (*rebel_string_get_slice_count)(const rebel_string *p_self, rebel_string p_splitter);
	rebel_string (*rebel_string_get_slice)(const rebel_string *p_self, rebel_string p_splitter, rebel_int p_slice);
	rebel_string (*rebel_string_get_slicec)(const rebel_string *p_self, wchar_t p_splitter, rebel_int p_slice);
	rebel_array (*rebel_string_split)(const rebel_string *p_self, const rebel_string *p_splitter);
	rebel_array (*rebel_string_split_allow_empty)(const rebel_string *p_self, const rebel_string *p_splitter);
	rebel_array (*rebel_string_split_floats)(const rebel_string *p_self, const rebel_string *p_splitter);
	rebel_array (*rebel_string_split_floats_allows_empty)(const rebel_string *p_self, const rebel_string *p_splitter);
	rebel_array (*rebel_string_split_floats_mk)(const rebel_string *p_self, const rebel_array *p_splitters);
	rebel_array (*rebel_string_split_floats_mk_allows_empty)(const rebel_string *p_self, const rebel_array *p_splitters);
	rebel_array (*rebel_string_split_ints)(const rebel_string *p_self, const rebel_string *p_splitter);
	rebel_array (*rebel_string_split_ints_allows_empty)(const rebel_string *p_self, const rebel_string *p_splitter);
	rebel_array (*rebel_string_split_ints_mk)(const rebel_string *p_self, const rebel_array *p_splitters);
	rebel_array (*rebel_string_split_ints_mk_allows_empty)(const rebel_string *p_self, const rebel_array *p_splitters);
	rebel_array (*rebel_string_split_spaces)(const rebel_string *p_self);
	wchar_t (*rebel_string_char_lowercase)(wchar_t p_char);
	wchar_t (*rebel_string_char_uppercase)(wchar_t p_char);
	rebel_string (*rebel_string_to_lower)(const rebel_string *p_self);
	rebel_string (*rebel_string_to_upper)(const rebel_string *p_self);
	rebel_string (*rebel_string_get_basename)(const rebel_string *p_self);
	rebel_string (*rebel_string_get_extension)(const rebel_string *p_self);
	rebel_string (*rebel_string_left)(const rebel_string *p_self, rebel_int p_pos);
	wchar_t (*rebel_string_ord_at)(const rebel_string *p_self, rebel_int p_idx);
	rebel_string (*rebel_string_plus_file)(const rebel_string *p_self, const rebel_string *p_file);
	rebel_string (*rebel_string_right)(const rebel_string *p_self, rebel_int p_pos);
	rebel_string (*rebel_string_strip_edges)(const rebel_string *p_self, rebel_bool p_left, rebel_bool p_right);
	rebel_string (*rebel_string_strip_escapes)(const rebel_string *p_self);
	void (*rebel_string_erase)(rebel_string *p_self, rebel_int p_pos, rebel_int p_chars);
	rebel_char_string (*rebel_string_ascii)(const rebel_string *p_self);
	rebel_char_string (*rebel_string_ascii_extended)(const rebel_string *p_self);
	rebel_char_string (*rebel_string_utf8)(const rebel_string *p_self);
	rebel_bool (*rebel_string_parse_utf8)(rebel_string *p_self, const char *p_utf8);
	rebel_bool (*rebel_string_parse_utf8_with_len)(rebel_string *p_self, const char *p_utf8, rebel_int p_len);
	rebel_string (*rebel_string_chars_to_utf8)(const char *p_utf8);
	rebel_string (*rebel_string_chars_to_utf8_with_len)(const char *p_utf8, rebel_int p_len);
	uint32_t (*rebel_string_hash)(const rebel_string *p_self);
	uint64_t (*rebel_string_hash64)(const rebel_string *p_self);
	uint32_t (*rebel_string_hash_chars)(const char *p_cstr);
	uint32_t (*rebel_string_hash_chars_with_len)(const char *p_cstr, rebel_int p_len);
	uint32_t (*rebel_string_hash_utf8_chars)(const wchar_t *p_str);
	uint32_t (*rebel_string_hash_utf8_chars_with_len)(const wchar_t *p_str, rebel_int p_len);
	rebel_pool_byte_array (*rebel_string_md5_buffer)(const rebel_string *p_self);
	rebel_string (*rebel_string_md5_text)(const rebel_string *p_self);
	rebel_pool_byte_array (*rebel_string_sha256_buffer)(const rebel_string *p_self);
	rebel_string (*rebel_string_sha256_text)(const rebel_string *p_self);
	rebel_bool (*rebel_string_empty)(const rebel_string *p_self);
	rebel_string (*rebel_string_get_base_dir)(const rebel_string *p_self);
	rebel_string (*rebel_string_get_file)(const rebel_string *p_self);
	rebel_string (*rebel_string_humanize_size)(uint64_t p_size);
	rebel_bool (*rebel_string_is_abs_path)(const rebel_string *p_self);
	rebel_bool (*rebel_string_is_rel_path)(const rebel_string *p_self);
	rebel_bool (*rebel_string_is_resource_file)(const rebel_string *p_self);
	rebel_string (*rebel_string_path_to)(const rebel_string *p_self, const rebel_string *p_path);
	rebel_string (*rebel_string_path_to_file)(const rebel_string *p_self, const rebel_string *p_path);
	rebel_string (*rebel_string_simplify_path)(const rebel_string *p_self);
	rebel_string (*rebel_string_c_escape)(const rebel_string *p_self);
	rebel_string (*rebel_string_c_escape_multiline)(const rebel_string *p_self);
	rebel_string (*rebel_string_c_unescape)(const rebel_string *p_self);
	rebel_string (*rebel_string_http_escape)(const rebel_string *p_self);
	rebel_string (*rebel_string_http_unescape)(const rebel_string *p_self);
	rebel_string (*rebel_string_json_escape)(const rebel_string *p_self);
	rebel_string (*rebel_string_word_wrap)(const rebel_string *p_self, rebel_int p_chars_per_line);
	rebel_string (*rebel_string_xml_escape)(const rebel_string *p_self);
	rebel_string (*rebel_string_xml_escape_with_quotes)(const rebel_string *p_self);
	rebel_string (*rebel_string_xml_unescape)(const rebel_string *p_self);
	rebel_string (*rebel_string_percent_decode)(const rebel_string *p_self);
	rebel_string (*rebel_string_percent_encode)(const rebel_string *p_self);
	rebel_bool (*rebel_string_is_valid_float)(const rebel_string *p_self);
	rebel_bool (*rebel_string_is_valid_hex_number)(const rebel_string *p_self, rebel_bool p_with_prefix);
	rebel_bool (*rebel_string_is_valid_html_color)(const rebel_string *p_self);
	rebel_bool (*rebel_string_is_valid_identifier)(const rebel_string *p_self);
	rebel_bool (*rebel_string_is_valid_integer)(const rebel_string *p_self);
	rebel_bool (*rebel_string_is_valid_ip_address)(const rebel_string *p_self);
	void (*rebel_string_destroy)(rebel_string *p_self);
	void (*rebel_string_name_new)(rebel_string_name *r_dest, const rebel_string *p_name);
	void (*rebel_string_name_new_data)(rebel_string_name *r_dest, const char *p_name);
	rebel_string (*rebel_string_name_get_name)(const rebel_string_name *p_self);
	uint32_t (*rebel_string_name_get_hash)(const rebel_string_name *p_self);
	const void *(*rebel_string_name_get_data_unique_pointer)(const rebel_string_name *p_self);
	rebel_bool (*rebel_string_name_operator_equal)(const rebel_string_name *p_self, const rebel_string_name *p_other);
	rebel_bool (*rebel_string_name_operator_less)(const rebel_string_name *p_self, const rebel_string_name *p_other);
	void (*rebel_string_name_destroy)(rebel_string_name *p_self);
	void (*rebel_object_destroy)(rebel_object *p_o);
	rebel_object *(*rebel_global_get_singleton)(char *p_name);
	rebel_method_bind *(*rebel_method_bind_get_method)(const char *p_classname, const char *p_methodname);
	void (*rebel_method_bind_ptrcall)(rebel_method_bind *p_method_bind, rebel_object *p_instance, const void **p_args, void *p_ret);
	rebel_variant (*rebel_method_bind_call)(rebel_method_bind *p_method_bind, rebel_object *p_instance, const rebel_variant **p_args, const int p_arg_count, rebel_variant_call_error *p_call_error);
	rebel_class_constructor (*rebel_get_class_constructor)(const char *p_classname);
	rebel_dictionary (*rebel_get_global_constants)();
	void (*rebel_register_native_call_type)(const char *call_type, native_call_cb p_callback);
	void *(*rebel_alloc)(int p_bytes);
	void *(*rebel_realloc)(void *p_ptr, int p_bytes);
	void (*rebel_free)(void *p_ptr);
	void (*rebel_print_error)(const char *p_description, const char *p_function, const char *p_file, int p_line);
	void (*rebel_print_warning)(const char *p_description, const char *p_function, const char *p_file, int p_line);
	void (*rebel_print)(const rebel_string *p_message);
} rebel_gdnative_core_api_struct;

#ifdef __cplusplus
}
#endif

#endif // GDNATIVE_API_STRUCT_H
