// SPDX-FileCopyrightText: 2025 Rebel SDK contributors
//
// SPDX-License-Identifier: MIT

#ifndef REBEL_GLOBALCONSTANTS_H
#define REBEL_GLOBALCONSTANTS_H

#include "api/gdnative_api_struct.gen.h"
#include "common/commontypes.h"
#include "common/ref.h"

#include <cstdint>

namespace Rebel {
class GlobalConstants : public Wrapped {
public:
    enum { CLASS_IS_SCRIPT = 0, };

    static const int BUTTON_LEFT = 1;
    static const int BUTTON_MASK_LEFT = 1;
    static const int BUTTON_MASK_MIDDLE = 4;
    static const int BUTTON_MASK_RIGHT = 2;
    static const int BUTTON_MASK_XBUTTON1 = 128;
    static const int BUTTON_MASK_XBUTTON2 = 256;
    static const int BUTTON_MIDDLE = 3;
    static const int BUTTON_RIGHT = 2;
    static const int BUTTON_WHEEL_DOWN = 5;
    static const int BUTTON_WHEEL_LEFT = 6;
    static const int BUTTON_WHEEL_RIGHT = 7;
    static const int BUTTON_WHEEL_UP = 4;
    static const int BUTTON_XBUTTON1 = 8;
    static const int BUTTON_XBUTTON2 = 9;
    static const int CORNER_BOTTOM_LEFT = 3;
    static const int CORNER_BOTTOM_RIGHT = 2;
    static const int CORNER_TOP_LEFT = 0;
    static const int CORNER_TOP_RIGHT = 1;
    static const int ERR_ALREADY_EXISTS = 32;
    static const int ERR_ALREADY_IN_USE = 22;
    static const int ERR_BUG = 47;
    static const int ERR_BUSY = 44;
    static const int ERR_CANT_ACQUIRE_RESOURCE = 28;
    static const int ERR_CANT_CONNECT = 25;
    static const int ERR_CANT_CREATE = 20;
    static const int ERR_CANT_FORK = 29;
    static const int ERR_CANT_OPEN = 19;
    static const int ERR_CANT_RESOLVE = 26;
    static const int ERR_COMPILATION_FAILED = 36;
    static const int ERR_CONNECTION_ERROR = 27;
    static const int ERR_CYCLIC_LINK = 40;
    static const int ERR_DATABASE_CANT_READ = 34;
    static const int ERR_DATABASE_CANT_WRITE = 35;
    static const int ERR_DOES_NOT_EXIST = 33;
    static const int ERR_DUPLICATE_SYMBOL = 42;
    static const int ERR_FILE_ALREADY_IN_USE = 11;
    static const int ERR_FILE_BAD_DRIVE = 8;
    static const int ERR_FILE_BAD_PATH = 9;
    static const int ERR_FILE_CANT_OPEN = 12;
    static const int ERR_FILE_CANT_READ = 14;
    static const int ERR_FILE_CANT_WRITE = 13;
    static const int ERR_FILE_CORRUPT = 16;
    static const int ERR_FILE_EOF = 18;
    static const int ERR_FILE_MISSING_DEPENDENCIES = 17;
    static const int ERR_FILE_NOT_FOUND = 7;
    static const int ERR_FILE_NO_PERMISSION = 10;
    static const int ERR_FILE_UNRECOGNIZED = 15;
    static const int ERR_HELP = 46;
    static const int ERR_INVALID_DATA = 30;
    static const int ERR_INVALID_DECLARATION = 41;
    static const int ERR_INVALID_PARAMETER = 31;
    static const int ERR_LINK_FAILED = 38;
    static const int ERR_LOCKED = 23;
    static const int ERR_METHOD_NOT_FOUND = 37;
    static const int ERR_OUT_OF_MEMORY = 6;
    static const int ERR_PARAMETER_RANGE_ERROR = 5;
    static const int ERR_PARSE_ERROR = 43;
    static const int ERR_PRINTER_ON_FIRE = 48;
    static const int ERR_QUERY_FAILED = 21;
    static const int ERR_SCRIPT_FAILED = 39;
    static const int ERR_SKIP = 45;
    static const int ERR_TIMEOUT = 24;
    static const int ERR_UNAUTHORIZED = 4;
    static const int ERR_UNAVAILABLE = 2;
    static const int ERR_UNCONFIGURED = 3;
    static const int FAILED = 1;
    static const int HALIGN_CENTER = 1;
    static const int HALIGN_LEFT = 0;
    static const int HALIGN_RIGHT = 2;
    static const int HORIZONTAL = 0;
    static const int JOY_ANALOG_L2 = 6;
    static const int JOY_ANALOG_LX = 0;
    static const int JOY_ANALOG_LY = 1;
    static const int JOY_ANALOG_R2 = 7;
    static const int JOY_ANALOG_RX = 2;
    static const int JOY_ANALOG_RY = 3;
    static const int JOY_AXIS_0 = 0;
    static const int JOY_AXIS_1 = 1;
    static const int JOY_AXIS_2 = 2;
    static const int JOY_AXIS_3 = 3;
    static const int JOY_AXIS_4 = 4;
    static const int JOY_AXIS_5 = 5;
    static const int JOY_AXIS_6 = 6;
    static const int JOY_AXIS_7 = 7;
    static const int JOY_AXIS_8 = 8;
    static const int JOY_AXIS_9 = 9;
    static const int JOY_AXIS_MAX = 10;
    static const int JOY_BUTTON_0 = 0;
    static const int JOY_BUTTON_1 = 1;
    static const int JOY_BUTTON_10 = 10;
    static const int JOY_BUTTON_11 = 11;
    static const int JOY_BUTTON_12 = 12;
    static const int JOY_BUTTON_13 = 13;
    static const int JOY_BUTTON_14 = 14;
    static const int JOY_BUTTON_15 = 15;
    static const int JOY_BUTTON_16 = 16;
    static const int JOY_BUTTON_17 = 17;
    static const int JOY_BUTTON_18 = 18;
    static const int JOY_BUTTON_19 = 19;
    static const int JOY_BUTTON_2 = 2;
    static const int JOY_BUTTON_20 = 20;
    static const int JOY_BUTTON_21 = 21;
    static const int JOY_BUTTON_22 = 22;
    static const int JOY_BUTTON_3 = 3;
    static const int JOY_BUTTON_4 = 4;
    static const int JOY_BUTTON_5 = 5;
    static const int JOY_BUTTON_6 = 6;
    static const int JOY_BUTTON_7 = 7;
    static const int JOY_BUTTON_8 = 8;
    static const int JOY_BUTTON_9 = 9;
    static const int JOY_BUTTON_MAX = 128;
    static const int JOY_DPAD_DOWN = 13;
    static const int JOY_DPAD_LEFT = 14;
    static const int JOY_DPAD_RIGHT = 15;
    static const int JOY_DPAD_UP = 12;
    static const int JOY_DS_A = 1;
    static const int JOY_DS_B = 0;
    static const int JOY_DS_X = 3;
    static const int JOY_DS_Y = 2;
    static const int JOY_GUIDE = 16;
    static const int JOY_INVALID_OPTION = -1;
    static const int JOY_L = 4;
    static const int JOY_L2 = 6;
    static const int JOY_L3 = 8;
    static const int JOY_MISC1 = 17;
    static const int JOY_OCULUS_AX = 7;
    static const int JOY_OCULUS_BY = 1;
    static const int JOY_OCULUS_MENU = 3;
    static const int JOY_OPENVR_MENU = 1;
    static const int JOY_OPENVR_TOUCHPADX = 0;
    static const int JOY_OPENVR_TOUCHPADY = 1;
    static const int JOY_PADDLE1 = 18;
    static const int JOY_PADDLE2 = 19;
    static const int JOY_PADDLE3 = 20;
    static const int JOY_PADDLE4 = 21;
    static const int JOY_R = 5;
    static const int JOY_R2 = 7;
    static const int JOY_R3 = 9;
    static const int JOY_SELECT = 10;
    static const int JOY_SONY_CIRCLE = 1;
    static const int JOY_SONY_SQUARE = 2;
    static const int JOY_SONY_TRIANGLE = 3;
    static const int JOY_SONY_X = 0;
    static const int JOY_START = 11;
    static const int JOY_TOUCHPAD = 22;
    static const int JOY_VR_ANALOG_GRIP = 4;
    static const int JOY_VR_ANALOG_TRIGGER = 2;
    static const int JOY_VR_GRIP = 2;
    static const int JOY_VR_PAD = 14;
    static const int JOY_VR_TRIGGER = 15;
    static const int JOY_XBOX_A = 0;
    static const int JOY_XBOX_B = 1;
    static const int JOY_XBOX_X = 2;
    static const int JOY_XBOX_Y = 3;
    static const int KEY_0 = 48;
    static const int KEY_1 = 49;
    static const int KEY_2 = 50;
    static const int KEY_3 = 51;
    static const int KEY_4 = 52;
    static const int KEY_5 = 53;
    static const int KEY_6 = 54;
    static const int KEY_7 = 55;
    static const int KEY_8 = 56;
    static const int KEY_9 = 57;
    static const int KEY_A = 65;
    static const int KEY_AACUTE = 193;
    static const int KEY_ACIRCUMFLEX = 194;
    static const int KEY_ACUTE = 180;
    static const int KEY_ADIAERESIS = 196;
    static const int KEY_AE = 198;
    static const int KEY_AGRAVE = 192;
    static const int KEY_ALT = 16777240;
    static const int KEY_AMPERSAND = 38;
    static const int KEY_APOSTROPHE = 39;
    static const int KEY_ARING = 197;
    static const int KEY_ASCIICIRCUM = 94;
    static const int KEY_ASCIITILDE = 126;
    static const int KEY_ASTERISK = 42;
    static const int KEY_AT = 64;
    static const int KEY_ATILDE = 195;
    static const int KEY_B = 66;
    static const int KEY_BACK = 16777280;
    static const int KEY_BACKSLASH = 92;
    static const int KEY_BACKSPACE = 16777220;
    static const int KEY_BACKTAB = 16777219;
    static const int KEY_BAR = 124;
    static const int KEY_BASSBOOST = 16777287;
    static const int KEY_BASSDOWN = 16777289;
    static const int KEY_BASSUP = 16777288;
    static const int KEY_BRACELEFT = 123;
    static const int KEY_BRACERIGHT = 125;
    static const int KEY_BRACKETLEFT = 91;
    static const int KEY_BRACKETRIGHT = 93;
    static const int KEY_BROKENBAR = 166;
    static const int KEY_C = 67;
    static const int KEY_CAPSLOCK = 16777241;
    static const int KEY_CCEDILLA = 199;
    static const int KEY_CEDILLA = 184;
    static const int KEY_CENT = 162;
    static const int KEY_CLEAR = 16777228;
    static const int KEY_CODE_MASK = 33554431;
    static const int KEY_COLON = 58;
    static const int KEY_COMMA = 44;
    static const int KEY_CONTROL = 16777238;
    static const int KEY_COPYRIGHT = 169;
    static const int KEY_CURRENCY = 164;
    static const int KEY_D = 68;
    static const int KEY_DEGREE = 176;
    static const int KEY_DELETE = 16777224;
    static const int KEY_DIAERESIS = 168;
    static const int KEY_DIRECTION_L = 16777266;
    static const int KEY_DIRECTION_R = 16777267;
    static const int KEY_DIVISION = 247;
    static const int KEY_DOLLAR = 36;
    static const int KEY_DOWN = 16777234;
    static const int KEY_E = 69;
    static const int KEY_EACUTE = 201;
    static const int KEY_ECIRCUMFLEX = 202;
    static const int KEY_EDIAERESIS = 203;
    static const int KEY_EGRAVE = 200;
    static const int KEY_END = 16777230;
    static const int KEY_ENTER = 16777221;
    static const int KEY_EQUAL = 61;
    static const int KEY_ESCAPE = 16777217;
    static const int KEY_ETH = 208;
    static const int KEY_EXCLAM = 33;
    static const int KEY_EXCLAMDOWN = 161;
    static const int KEY_F = 70;
    static const int KEY_F1 = 16777244;
    static const int KEY_F10 = 16777253;
    static const int KEY_F11 = 16777254;
    static const int KEY_F12 = 16777255;
    static const int KEY_F13 = 16777256;
    static const int KEY_F14 = 16777257;
    static const int KEY_F15 = 16777258;
    static const int KEY_F16 = 16777259;
    static const int KEY_F2 = 16777245;
    static const int KEY_F3 = 16777246;
    static const int KEY_F4 = 16777247;
    static const int KEY_F5 = 16777248;
    static const int KEY_F6 = 16777249;
    static const int KEY_F7 = 16777250;
    static const int KEY_F8 = 16777251;
    static const int KEY_F9 = 16777252;
    static const int KEY_FAVORITES = 16777298;
    static const int KEY_FORWARD = 16777281;
    static const int KEY_G = 71;
    static const int KEY_GREATER = 62;
    static const int KEY_GUILLEMOTLEFT = 171;
    static const int KEY_GUILLEMOTRIGHT = 187;
    static const int KEY_H = 72;
    static const int KEY_HELP = 16777265;
    static const int KEY_HOME = 16777229;
    static const int KEY_HOMEPAGE = 16777297;
    static const int KEY_HYPER_L = 16777263;
    static const int KEY_HYPER_R = 16777264;
    static const int KEY_HYPHEN = 173;
    static const int KEY_I = 73;
    static const int KEY_IACUTE = 205;
    static const int KEY_ICIRCUMFLEX = 206;
    static const int KEY_IDIAERESIS = 207;
    static const int KEY_IGRAVE = 204;
    static const int KEY_INSERT = 16777223;
    static const int KEY_J = 74;
    static const int KEY_K = 75;
    static const int KEY_KP_0 = 16777350;
    static const int KEY_KP_1 = 16777351;
    static const int KEY_KP_2 = 16777352;
    static const int KEY_KP_3 = 16777353;
    static const int KEY_KP_4 = 16777354;
    static const int KEY_KP_5 = 16777355;
    static const int KEY_KP_6 = 16777356;
    static const int KEY_KP_7 = 16777357;
    static const int KEY_KP_8 = 16777358;
    static const int KEY_KP_9 = 16777359;
    static const int KEY_KP_ADD = 16777349;
    static const int KEY_KP_DIVIDE = 16777346;
    static const int KEY_KP_ENTER = 16777222;
    static const int KEY_KP_MULTIPLY = 16777345;
    static const int KEY_KP_PERIOD = 16777348;
    static const int KEY_KP_SUBTRACT = 16777347;
    static const int KEY_L = 76;
    static const int KEY_LAUNCH0 = 16777304;
    static const int KEY_LAUNCH1 = 16777305;
    static const int KEY_LAUNCH2 = 16777306;
    static const int KEY_LAUNCH3 = 16777307;
    static const int KEY_LAUNCH4 = 16777308;
    static const int KEY_LAUNCH5 = 16777309;
    static const int KEY_LAUNCH6 = 16777310;
    static const int KEY_LAUNCH7 = 16777311;
    static const int KEY_LAUNCH8 = 16777312;
    static const int KEY_LAUNCH9 = 16777313;
    static const int KEY_LAUNCHA = 16777314;
    static const int KEY_LAUNCHB = 16777315;
    static const int KEY_LAUNCHC = 16777316;
    static const int KEY_LAUNCHD = 16777317;
    static const int KEY_LAUNCHE = 16777318;
    static const int KEY_LAUNCHF = 16777319;
    static const int KEY_LAUNCHMAIL = 16777302;
    static const int KEY_LAUNCHMEDIA = 16777303;
    static const int KEY_LEFT = 16777231;
    static const int KEY_LESS = 60;
    static const int KEY_M = 77;
    static const int KEY_MACRON = 175;
    static const int KEY_MASCULINE = 186;
    static const int KEY_MASK_ALT = 67108864;
    static const int KEY_MASK_CMD = 268435456;
    static const int KEY_MASK_CTRL = 268435456;
    static const int KEY_MASK_GROUP_SWITCH = 1073741824;
    static const int KEY_MASK_KPAD = 536870912;
    static const int KEY_MASK_META = 134217728;
    static const int KEY_MASK_SHIFT = 33554432;
    static const int KEY_MEDIANEXT = 16777295;
    static const int KEY_MEDIAPLAY = 16777292;
    static const int KEY_MEDIAPREVIOUS = 16777294;
    static const int KEY_MEDIARECORD = 16777296;
    static const int KEY_MEDIASTOP = 16777293;
    static const int KEY_MENU = 16777262;
    static const int KEY_META = 16777239;
    static const int KEY_MINUS = 45;
    static const int KEY_MODIFIER_MASK = -16777216;
    static const int KEY_MU = 181;
    static const int KEY_MULTIPLY = 215;
    static const int KEY_N = 78;
    static const int KEY_NOBREAKSPACE = 160;
    static const int KEY_NOTSIGN = 172;
    static const int KEY_NTILDE = 209;
    static const int KEY_NUMBERSIGN = 35;
    static const int KEY_NUMLOCK = 16777242;
    static const int KEY_O = 79;
    static const int KEY_OACUTE = 211;
    static const int KEY_OCIRCUMFLEX = 212;
    static const int KEY_ODIAERESIS = 214;
    static const int KEY_OGRAVE = 210;
    static const int KEY_ONEHALF = 189;
    static const int KEY_ONEQUARTER = 188;
    static const int KEY_ONESUPERIOR = 185;
    static const int KEY_OOBLIQUE = 216;
    static const int KEY_OPENURL = 16777301;
    static const int KEY_ORDFEMININE = 170;
    static const int KEY_OTILDE = 213;
    static const int KEY_P = 80;
    static const int KEY_PAGEDOWN = 16777236;
    static const int KEY_PAGEUP = 16777235;
    static const int KEY_PARAGRAPH = 182;
    static const int KEY_PARENLEFT = 40;
    static const int KEY_PARENRIGHT = 41;
    static const int KEY_PAUSE = 16777225;
    static const int KEY_PERCENT = 37;
    static const int KEY_PERIOD = 46;
    static const int KEY_PERIODCENTERED = 183;
    static const int KEY_PLUS = 43;
    static const int KEY_PLUSMINUS = 177;
    static const int KEY_PRINT = 16777226;
    static const int KEY_Q = 81;
    static const int KEY_QUESTION = 63;
    static const int KEY_QUESTIONDOWN = 191;
    static const int KEY_QUOTEDBL = 34;
    static const int KEY_QUOTELEFT = 96;
    static const int KEY_R = 82;
    static const int KEY_REFRESH = 16777283;
    static const int KEY_REGISTERED = 174;
    static const int KEY_RIGHT = 16777233;
    static const int KEY_S = 83;
    static const int KEY_SCROLLLOCK = 16777243;
    static const int KEY_SEARCH = 16777299;
    static const int KEY_SECTION = 167;
    static const int KEY_SEMICOLON = 59;
    static const int KEY_SHIFT = 16777237;
    static const int KEY_SLASH = 47;
    static const int KEY_SPACE = 32;
    static const int KEY_SSHARP = 223;
    static const int KEY_STANDBY = 16777300;
    static const int KEY_STERLING = 163;
    static const int KEY_STOP = 16777282;
    static const int KEY_SUPER_L = 16777260;
    static const int KEY_SUPER_R = 16777261;
    static const int KEY_SYSREQ = 16777227;
    static const int KEY_T = 84;
    static const int KEY_TAB = 16777218;
    static const int KEY_THORN = 222;
    static const int KEY_THREEQUARTERS = 190;
    static const int KEY_THREESUPERIOR = 179;
    static const int KEY_TREBLEDOWN = 16777291;
    static const int KEY_TREBLEUP = 16777290;
    static const int KEY_TWOSUPERIOR = 178;
    static const int KEY_U = 85;
    static const int KEY_UACUTE = 218;
    static const int KEY_UCIRCUMFLEX = 219;
    static const int KEY_UDIAERESIS = 220;
    static const int KEY_UGRAVE = 217;
    static const int KEY_UNDERSCORE = 95;
    static const int KEY_UNKNOWN = 33554431;
    static const int KEY_UP = 16777232;
    static const int KEY_V = 86;
    static const int KEY_VOLUMEDOWN = 16777284;
    static const int KEY_VOLUMEMUTE = 16777285;
    static const int KEY_VOLUMEUP = 16777286;
    static const int KEY_W = 87;
    static const int KEY_X = 88;
    static const int KEY_Y = 89;
    static const int KEY_YACUTE = 221;
    static const int KEY_YDIAERESIS = 255;
    static const int KEY_YEN = 165;
    static const int KEY_Z = 90;
    static const int MARGIN_BOTTOM = 3;
    static const int MARGIN_LEFT = 0;
    static const int MARGIN_RIGHT = 2;
    static const int MARGIN_TOP = 1;
    static const int METHOD_FLAGS_DEFAULT = 1;
    static const int METHOD_FLAG_CONST = 8;
    static const int METHOD_FLAG_EDITOR = 2;
    static const int METHOD_FLAG_FROM_SCRIPT = 64;
    static const int METHOD_FLAG_NORMAL = 1;
    static const int METHOD_FLAG_NOSCRIPT = 4;
    static const int METHOD_FLAG_REVERSE = 16;
    static const int METHOD_FLAG_VIRTUAL = 32;
    static const int MIDI_MESSAGE_AFTERTOUCH = 10;
    static const int MIDI_MESSAGE_CHANNEL_PRESSURE = 13;
    static const int MIDI_MESSAGE_CONTROL_CHANGE = 11;
    static const int MIDI_MESSAGE_NOTE_OFF = 8;
    static const int MIDI_MESSAGE_NOTE_ON = 9;
    static const int MIDI_MESSAGE_PITCH_BEND = 14;
    static const int MIDI_MESSAGE_PROGRAM_CHANGE = 12;
    static const int OK = 0;
    static const int OP_ADD = 6;
    static const int OP_AND = 20;
    static const int OP_BIT_AND = 16;
    static const int OP_BIT_NEGATE = 19;
    static const int OP_BIT_OR = 17;
    static const int OP_BIT_XOR = 18;
    static const int OP_DIVIDE = 9;
    static const int OP_EQUAL = 0;
    static const int OP_GREATER = 4;
    static const int OP_GREATER_EQUAL = 5;
    static const int OP_IN = 24;
    static const int OP_LESS = 2;
    static const int OP_LESS_EQUAL = 3;
    static const int OP_MAX = 25;
    static const int OP_MODULE = 12;
    static const int OP_MULTIPLY = 8;
    static const int OP_NEGATE = 10;
    static const int OP_NOT = 23;
    static const int OP_NOT_EQUAL = 1;
    static const int OP_OR = 21;
    static const int OP_POSITIVE = 11;
    static const int OP_SHIFT_LEFT = 14;
    static const int OP_SHIFT_RIGHT = 15;
    static const int OP_STRING_CONCAT = 13;
    static const int OP_SUBTRACT = 7;
    static const int OP_XOR = 22;
    static const int PROPERTY_HINT_COLOR_NO_ALPHA = 20;
    static const int PROPERTY_HINT_DIR = 14;
    static const int PROPERTY_HINT_ENUM = 3;
    static const int PROPERTY_HINT_EXP_EASING = 4;
    static const int PROPERTY_HINT_EXP_RANGE = 2;
    static const int PROPERTY_HINT_FILE = 13;
    static const int PROPERTY_HINT_FLAGS = 8;
    static const int PROPERTY_HINT_GLOBAL_DIR = 16;
    static const int PROPERTY_HINT_GLOBAL_FILE = 15;
    static const int PROPERTY_HINT_IMAGE_COMPRESS_LOSSLESS = 22;
    static const int PROPERTY_HINT_IMAGE_COMPRESS_LOSSY = 21;
    static const int PROPERTY_HINT_KEY_ACCEL = 7;
    static const int PROPERTY_HINT_LAYERS_2D_PHYSICS = 10;
    static const int PROPERTY_HINT_LAYERS_2D_RENDER = 9;
    static const int PROPERTY_HINT_LAYERS_3D_PHYSICS = 12;
    static const int PROPERTY_HINT_LAYERS_3D_RENDER = 11;
    static const int PROPERTY_HINT_LENGTH = 5;
    static const int PROPERTY_HINT_MULTILINE_TEXT = 18;
    static const int PROPERTY_HINT_NONE = 0;
    static const int PROPERTY_HINT_PLACEHOLDER_TEXT = 19;
    static const int PROPERTY_HINT_RANGE = 1;
    static const int PROPERTY_HINT_RESOURCE_TYPE = 17;
    static const int PROPERTY_USAGE_CATEGORY = 256;
    static const int PROPERTY_USAGE_CHECKABLE = 16;
    static const int PROPERTY_USAGE_CHECKED = 32;
    static const int PROPERTY_USAGE_DEFAULT = 7;
    static const int PROPERTY_USAGE_DEFAULT_INTL = 71;
    static const int PROPERTY_USAGE_EDITOR = 2;
    static const int PROPERTY_USAGE_EDITOR_HELPER = 8;
    static const int PROPERTY_USAGE_GROUP = 128;
    static const int PROPERTY_USAGE_INTERNATIONALIZED = 64;
    static const int PROPERTY_USAGE_NETWORK = 4;
    static const int PROPERTY_USAGE_NOEDITOR = 5;
    static const int PROPERTY_USAGE_NO_INSTANCE_STATE = 2048;
    static const int PROPERTY_USAGE_RESTART_IF_CHANGED = 4096;
    static const int PROPERTY_USAGE_SCRIPT_VARIABLE = 8192;
    static const int PROPERTY_USAGE_STORAGE = 1;
    static const int SPKEY = 16777216;
    static const int TYPE_AABB = 11;
    static const int TYPE_ARRAY = 19;
    static const int TYPE_BASIS = 12;
    static const int TYPE_BOOL = 1;
    static const int TYPE_COLOR = 14;
    static const int TYPE_COLOR_ARRAY = 26;
    static const int TYPE_DICTIONARY = 18;
    static const int TYPE_INT = 2;
    static const int TYPE_INT_ARRAY = 21;
    static const int TYPE_MAX = 27;
    static const int TYPE_NIL = 0;
    static const int TYPE_NODE_PATH = 15;
    static const int TYPE_OBJECT = 17;
    static const int TYPE_PLANE = 9;
    static const int TYPE_QUAT = 10;
    static const int TYPE_RAW_ARRAY = 20;
    static const int TYPE_REAL = 3;
    static const int TYPE_REAL_ARRAY = 22;
    static const int TYPE_RECT2 = 6;
    static const int TYPE_RID = 16;
    static const int TYPE_STRING = 4;
    static const int TYPE_STRING_ARRAY = 23;
    static const int TYPE_TRANSFORM = 13;
    static const int TYPE_TRANSFORM2D = 8;
    static const int TYPE_VECTOR2 = 5;
    static const int TYPE_VECTOR2_ARRAY = 24;
    static const int TYPE_VECTOR3 = 7;
    static const int TYPE_VECTOR3_ARRAY = 25;
    static const int VALIGN_BOTTOM = 2;
    static const int VALIGN_CENTER = 1;
    static const int VALIGN_TOP = 0;
    static const int VERTICAL = 1;

    static inline GlobalConstants* get_singleton() {
        if (!GlobalConstants::singleton) {
            GlobalConstants::singleton = new GlobalConstants;
        }
        return GlobalConstants::singleton;
    }

    static void init_method_bindings();

    inline static size_t get_class_tag() {
        return (size_t)class_tag;
    }

    inline static const char* _get_class_name() {
        return "GlobalConstants";
    }

    inline static const char* get_rebel_class_name() {
        return "GlobalConstants";
    }

    inline static Object* from_variant(Variant variant) {
        rebel_object* object = (rebel_object*)variant;
        if (!object) {
            return nullptr;
        }
        return (Object*)nativescript_1_1_api->
            rebel_nativescript_get_instance_binding_data(
                RegisterState::language_index,
                object
            );
    }

private:
    GlobalConstants();
    static GlobalConstants* singleton;

    struct MethodBindings {
    };

    static MethodBindings method_bindings;
    static void* class_tag;
};
} // namespace Rebel

#endif // REBEL_GLOBALCONSTANTS_H
